### ISSUE TITLE
Fix S2933: Code Fix should handle regions

### ISSUE THREAD

**Issue by nnpcYvIVl** [SonarSource/sonar-csharp#1009]
### Description

```
#region Test
string teststring = null;
#endregion
```

The S2933 code fix outputs broken code:

```
readonly
#region Test
string teststring = null;
#endregion
```
### Related information

* SonarC# Version Latest
* Visual Studio 15.5.1

**Comment by Evangelink** [comment]
Hi @nnpcYvIVl,

Thanks for the feedback. I have managed to reproduce the issue.
