### ISSUE TITLE
Fix S2187: rule should not warn on MSTest when using DataTestMethodAttribute

### ISSUE THREAD

**Issue by shuebner** [SonarSource/sonar-csharp#1010]
### Description

S2187 should not warn on MSTest [DataTestMethod]

### Repro steps

Create an MSTest [TestClass] with a single method attributed with [DataTestMethod].

### Expected behavior

Sonar does not issue a S2187 warning on the class.

### Actual behavior

Sonar issues a S2187 warning on the class.

### Related information

* SonarC# Version 6.6.0.3969
* Visual Studio Version 2017

**Comment by Evangelink** [comment]
Hi @shuebner,

Thanks for raising this issue and thanks for the associated PR.
