### ISSUE TITLE
Sonar java plugin

### ISSUE THREAD

**Issue by rexuekonglong** [SonarSource/sonar-csharp#1035]
### Description

No more scan  java source code ,What's going on ?

### Repro steps

1."Please provide compiled classes of your project with sonar.java.binaries property" 
    sonar-java-plugin 50(build 12796)

2.When Sonarqube 6.3.0 the SonarJava plugin worked and no need the compiled classes file

### Expected behavior

My  java project  property
sonar.projectKey = test_java
sonar.projectName = test_java
sonar.projectVersion = 1.0
sonar.sources = .
sonar.language=java
sonar.java.source=1.7

### Related information

*Sonarqube 6.7.1
* SonarJava 5.0 (build 12796)
* SonarScan 3.0.3
* SonarQube Scanner for Jenkins 2.6.1

**Comment by valhristov** [comment]
Hi @rexuekonglong, this repository is for SonarC# only, as far as I can understand, your question is about SonarJava. Could you please ask it again on the following Google group? It is the right place for SonarJava feedback: https://groups.google.com/forum/#!forum/sonarqube

**Comment by rexuekonglong** [comment]
@valhristov   I'm sorry , wrong place to write.

**Comment by rexuekonglong** [comment]
@valhristov  @valhristov I'm sorry , wrong place to write.
