### ISSUE TITLE
Rule S3242: False positives

### ISSUE THREAD

**Issue by MaxTranced** [SonarSource/sonar-csharp#1036]
### Description

Rule S3242 is flagging what I believe to be false positives for these cases:

> Consider using more general type 'System.Xml.XmlNode' instead of 'System.Xml.XmlDocument'

Semantically different classes. This distinction might be part of an API decision (for example: do I sign an entire document or just a node?).

> Consider using more general type 'System.IO.FileSystemInfo' instead of 'System.IO.FileInfo'

Semantically different. Some of the methods (for example Exists()) behave differently.
https://msdn.microsoft.com/en-us/library/system.io.fileinfo.exists(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.io.filesysteminfo.exists(v=vs.110).aspx

> Consider using more general type 'System.Security.Cryptography.ICspAsymmetricAlgorithm' instead of 'System.Security.Cryptography.RSACryptoServiceProvider'

The cryptographic algorithm used might matter when implementing a certain standard or protocol.

> Consider using more general type 'System.Collections.IDictionary' instead of 'System.Collections.Specialized.IOrderedDictionary'

The ordered dictionary cannot be replaced by a non-ordered dictionary in cases where ordering matters (duh!).

### Repro steps

N/A

### Expected behavior

Code falling into one of the cases above does not trigger S3242

### Actual behavior

N/A

### Known workarounds

N/A

### Related information

* SonarC# 6.6 (build 3969)
* Visual Studio 2017 (15.5.2)
* Scanner for MSBuild: 4.0.2.892

**Comment by valhristov** [comment]
Hi @MaxTranced thanks for the feedback! You are right, in many cases it makes sense to have arguments that are not the most base-level class and perhaps we should limit this rule to simple collections (IEnumerable, IList, ICollection, etc.)...

**Comment by MaxTranced** [comment]
@valhristov: that sounds like a reasonable compromise.

Maybe the IDictionary case could be included in a rule such as: limit the rule to simple collections, do not trigger for interfaces that inherit other interfaces, nor for collections in the "Specialized" namespace.

**Comment by paulhickman-a365** [comment]
Suggesting that various collection classes should be replaced with IEnumerable is also dangerous, as some IEnumerables can only be enumerated once (e.g. those created from a method using yield return). If the method causes the enumerable to be enumerated twice, this could introduce unexpected bugs.

**Comment by valhristov** [comment]
We discussed this rule in the team and we think there is no reliable way to guess what the developer meant when he wrote the code. Sometimes it is ok to use a base class, sometimes it is not, depending on the context and limiting the rule to just collections will still generate false positives.

Since the severity of this rule is the lowest possible and it is not included in the default Quality Profile, we would recommend interpreting its issues as places that deserve the attention of the developer in case he wants to inspect the arguments which could be changed.

So our preference would be to leave the rule as it is for now.

**Comment by MaxTranced** [comment]
Makes sense, @valhristov . Maybe a short mention of this in the rule description would help.

Thank you!

**Comment by Evangelink** [comment]
That's a good suggestion to mention ragt in the rule description!
