### ISSUE TITLE
Fix S1168: "Return empty collection" should not raise when the method return type is XmlNode

### ISSUE THREAD

**Issue by MaxTranced** [SonarSource/sonar-csharp#1037]
### Description

<pre><code>
        public static XmlNode TryGetSingleChildByName(XmlNode xmlNode, string elementName)
        {
            IList<XmlNode> elements = GetChildNodesMatchingName(xmlNode, elementName);
            switch (elements.Count)
            {
                case 0:
                    {
                        return null;
                    }
                case 1:
                    {
                        return elements[0];
                    }

                default:
                    {
                        throw new InvalidOperationException();
                    }
            }
        }
</code></pre>

triggers

> warning S1168: Return an empty collection instead of null

### Repro steps

Either open a class containing the above code snippet in Visual Studio or run an analysis on one such file.

### Expected behavior

S1168 should not be triggered as the return type of the method is not a collection.

### Actual behavior

S1168 is triggered.

### Known workarounds

N/A

### Related information

* SonarC# 6.6 (build 3969)
* Visual Studio 2017 (15.5.2) (also triggered if having https://www.sonarlint.org/visualstudio/ installed, version 3.8.1.2823 )
* Scanner for MSBuild: 4.0.2.892

**Comment by MaxTranced** [comment]
In fact, the FP might be caused by the fact that XmlNode implements IEnumerable, rather than the fact that one of the switch branches returns a collection element... Just guessing here.

**Comment by valhristov** [comment]
As far as I can see, you are right - the rule is triggered because XmlNode implements IEnumerable, we will add exceptions for XmlNode and its descendants.
