### ISSUE TITLE
Rule S4260: "ConstructorArgument" parameters should exist in constructors

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-csharp#1055]
[RSPEC-4260](https://jira.sonarsource.com/browse/RSPEC-4260)

When creating a custom Markup Extension that accepts parameters in WPF, the ConstructorArgument markup must be used to identify the discrete properties that match these parameters. However since this is done via a string, the compiler will not notice if there are typos.

**Comment by valhristov** [comment]
Was already implemented
