### ISSUE TITLE
Rule S3060: "is" should not be used with "this"

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-csharp#1066]
[RSPEC-3060](https://jira.sonarsource.com/browse/RSPEC-3060)

There's no valid reason to test this with is. The only plausible explanation for such a test is that you're executing code in a parent class conditionally based on the kind of child class this is. But code that's specific to a child class should be in that child class, not in the parent.

**Comment by sebilm** [comment]
Wouldn't it be a valid option to check this on an interface? I do so and SonarQube does not like it.
