### ISSUE TITLE
Rule S3358: Ternary operators should not be nested

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-csharp#1073]
[RSPEC-3358](https://jira.sonarsource.com/browse/RSPEC-3358)

Just because you can do something, doesn't mean you should, and that's the case with nested ternary operations. Nesting ternary operators results in the kind of code that may seem clear as day when you write it, but six months later will leave maintainers (or worse - future you) scratching their heads and cursing.

common rule

**Comment by SanjanaTailor** [comment]
how to disable this rule ?

**Comment by vineethasree** [comment]
Hi @pavel-mikula-sonarsource  can u please tell what need to be added in .editorconfig file to disable the nested ternary operator ?

**Comment by pavel-mikula-sonarsource** [comment]
Analysis configuration is described int he documentation: https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022

This is the fragment to disable S3358 rule:
```
dotnet_diagnostic.S3358.severity = none
```
