### ISSUE TITLE
Rule S2302: 'nameof' should be used

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-csharp#1075]
[RSPEC-2302](https://jira.sonarsource.com/browse/RSPEC-2302)

Because parameter names could be changed during refactoring, they should not be spelled out literally in strings. Instead, use `nameof()`, and the string that's output will always be correct.

**Comment by Evangelink** [comment]
Let's update the RSPEC description to mention the locations where the rule will check for it.

**Comment by MaxTranced** [comment]
This has the same issue as
https://github.com/dotnet/roslyn-analyzers/issues/1524

The rule should not be triggered for projects that set the advanced build setting "Language version" to C# 5 (any version prior to 6).

**Comment by michalb-sonar** [comment]
Thanks for suggestion @MaxTranced! I've created a ticket: https://github.com/SonarSource/sonar-csharp/issues/1162
