### ISSUE TITLE
Rule S3923: All branches in a conditional structure should not have exactly the same implementation

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonar-csharp#1079]
#153 has been fixed but looks like [RSPEC-3923](https://jira.sonarsource.com/browse/RSPEC-3923) has not been added while fixing [RSPEC-1871](https://jira.sonarsource.com/browse/RSPEC-1871)
common rule

**Comment by fmallet** [comment]
Ping, this rule allows to find highly relevant issues.

**Comment by valhristov** [comment]
We will implement all common rules in a subsequent sprint (both VB.NET and C#). 7.1 is focused only on fixing rules.

**Comment by fmallet** [comment]
Let me give a new try @valhristov : this rule is highly valuable and comes almost for free so could we consider to implement it ? :)

**Comment by Evangelink** [comment]
@fmallet Happy? :)

**Comment by Evangelink** [comment]
(not merged yet)
