### ISSUE TITLE
Scanner fails with forbidden without 'Browse' permission

### ISSUE THREAD

**Issue by koczkatamas** [SonarSource/sonar-csharp#1081]
### Description

SonarQube.Scanner.MSBuild.exe throws `The remote server returned an error: (403) Forbidden.` when it tries to access the URL `http://localhost:9000/api/settings/values?component=XXXX` if I don't give "Browse" permission for its user.

I would expect based on the description of the "Execute Analysis" permission on the SonarQube UI that the scanner won't need "Browse" permission too:

> Ability to get all settings required to perform an analysis (including the secured settings like passwords) and to push analysis results to the SonarQube server.

I did not find this requirement in the documentation.

Please 

- either make the scanner work without the Browse permission if the current behavior is not the intended one
- or document this requirement somewhere that the Browse permission is needed indeed 
- and/or show an additional error message if the `api/settings/values` call fails with `(403) Forbidden` explaining that this scanner also requires Browse permission

If we decide which is the correct way to go, and I can help by looking into the issue and submitting a PR if needed.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a new user used only by the scanner (eg. `scanner-user`)
2. Create a token for the newly created user
3. Go to a private project's permissions page (eg. http://localhost:9000/project_roles?id=testproject)
4. Add `scanner-user` to the project with only `Execute Analysis` permission (do NOT give `Browse` permission)
5. Execute `SonarQube.Scanner.MSBuild.exe begin /k:testproject /d:sonar.login=<token_created_in_step2>`

### Expected behavior

Analysis runs without errors OR an error message is displayed mentioning that this scanner requires Browse permission.

### Actual behavior

Scanner fails with `Failed to request and parse 'http://localhost:9000/api/settings/values?component=testproject': The remote server returned an error: (403) Forbidden.` error message.

### Known workarounds

Give the scanner's user `Browse` permission.

### Related information

* SonarC# Version: 4.0.2.982
* Visual Studio Version: 2017
* If running through the Scanner for MSBuild, its version: N/A

**Comment by valhristov** [comment]
For the time being the best and easiest solution would be to improve the error message and document the needed permissions to execute analysis. We can do that for the next release of Scanner for MSBuild.

I would prefer having the "Execute Analysis" to automatically imply that you have "Browse", but unfortunately [the project permissions are not cumulative](https://docs.sonarqube.org/display/SONAR/Authorization#Authorization-ProjectPermissions) and you need to specify both. At least we can help you find what's wrong, exactly as you suggested.

Thanks for the feedback!

**Comment by valhristov** [comment]
That's the corresponding ticket for Scanner for MSBuild:
https://jira.sonarsource.com/browse/SONARMSBRU-367

**Comment by bellingard** [comment]
The version of the SonarQube server was not specified in the ticket, so I can't guarantee what I'm going to say, but: it seems very similar to [SONAR-10323](https://jira.sonarsource.com/browse/SONAR-10323), a bug found on SQ 6.7 and 7.0.

**Comment by valhristov** [comment]
@bellingard I don't know if [SONAR-10323](https://jira.sonarsource.com/browse/SONAR-10323) is related, but the problem should happen even with very old versions of SonarQube. We get 403 Forbidden when we try to download the properties of the SonarQube project: `api/server/version` or `api/settings/values?component=projectKey` (after 6.3) and `Browse` permission is not set.
