### ISSUE TITLE
Fix S1226: Rule should not throw if read before being assigned to

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-csharp#1082]
The rule states that a parameter should not be assigned a value to before being read. 

In this case we raise while the value was read before (the if condition).
https://peach.sonarsource.com/project/issues?id=akka&issues=AWDbc_bt6nNSSlBMG34a&open=AWDbc_bt6nNSSlBMG34a

**Comment by valhristov** [comment]
That's basically request to rewrite the rule.

**Comment by Evangelink** [comment]
It is indeed. We do not respect the RSPEC

**Comment by Evangelink** [comment]
Duplicate of #630
