### ISSUE TITLE
Fix S4056: False positives when calling Convert.ToInt32(double x)

### ISSUE THREAD

**Issue by michivo** [SonarSource/sonar-csharp#1083]
### Description

When converting a double value to an integer value with Convert.ToInt32(double x), I get an unexpected S4056 error ("Use the overload that takes a CultureInfo or IFormatProvider parameter).

### Repro steps

Sample code line:

`int x = Convert.ToInt32(3.5);`

### Expected behavior

No error. There is no overload Convert.ToInt32(double value, CultureInfo ci) or Convert.ToInt32(double value, IFormatProvider formatProvider). There is an overload Convert.ToInt32(object o, IFormatProvider formatProvider), but I do not want to call the overload with an object parameter.

### Actual behavior

False detection of Error S4056: Use the overload that takes a 'CultureInfo' or 'IFormatProvider' parameter.

### Related information

* SonarC# Version 6.4.1.3596
* Visual Studio Version 14.0.25425.01 Update 3 (VS Professional 2015)

**Comment by Evangelink** [comment]
Hi @michivo,

There is an overload for `object` with the `CultureInfo`. I need to dig in a bit to see if there is any difference between the overloads.

I'll keep you posted with the updates of the tests.
