### ISSUE TITLE
Update plugin properties to declare them as multi-values property

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-csharp#1106]
When running the scanner for msbuild against a recent version of SonarQube the analysis will display the following kind of warnings: `WARNING: WARN: Property 'sonar.cs.opencover.reportsPaths' is not declared as multi-values/property set but was read using 'getStringArray' method. The SonarQube plugin declaring this property should be updated.`. These warnings can be a concern for end-users while they are only targeting plugin developers and so should be fixed ASAP.

**Comment by markdemich** [comment]
Are these warning benign though?

**Comment by Evangelink** [comment]
Hi @markdemich,

They are! They are only related to an internal change of API on the plugins and are meant to help us (developers) to see that we haven't updated the usage.
