### ISSUE TITLE
Rule S4428: "PartCreationPolicyAttribute" should be used with "ExportAttribute"

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-csharp#1166]
[RSPEC-4428](https://jira.sonarsource.com/browse/RSPEC-4428)

The PartCreationPolicyAttribute attribute, which is part of the Managed Extensibility Framework (MEF), is used to specify how the exported object will be created. Therefore it doesn't make sense not to export this a class with this attribute using the ExportAttribute attribute.

**Comment by fatihcetin** [comment]
This rule is not working proper with 2 conditions : 

1. If you use a customExportAtribute that is derived from ExportAttribute.
2. If you have InheritedExport attribute on an interface and use PartCreationPolicyAttribute on a class that is implementing that interface.
