### ISSUE TITLE
Rule S1118 (Utility classes should not have public constructors) ignores its exceptions

### ISSUE THREAD

**Issue by Michaelvsk** [SonarSource/sonar-csharp#1175]
### Description

Rule S1118 mentions the exception that classes containing `public static void main(String[] args)` will be ignored. This is not the case.

Original text from Rule description:
> Exceptions
> When class contains `public static void main(String[] args)` method it is not considered as utility class and will be ignored by this rule.

### Repro steps

The following code shows up as a code smell caused by S1118.

```csharp
public class Program
{
    public static void Main(string[] args)
    {
    }
}
```

### Related information

* SonarQube Version: 7.0.0.36138
* SonarC# Version: 6.8.1 (build 4648)
* Visual Studio Version: 15.5.6
* SonarQube Scanner for MSBuild Version: 4.0.2

**Comment by Evangelink** [comment]
Hi @Michaelvsk,

Thanks for the feedback. There was indeed a change (exception section was added) without us noticing so that's why it is not implemented.

We are not really fan of the exception and we were thinking about removing it. Would it be a problem for you? If so could you explain why?

**Comment by Michaelvsk** [comment]
I'm neither a fan of exceptions. The value of this exception isn't that high. Because then you could also start adding several exceptions for the default config classes of ASP.NET Core which come with a single static method in a non-static class. And there are probably a lot more application types which use such a construct. 

So feel free to remove that text from the description. Just want to make sure that the behavior and explanation do match. :)

**Comment by Evangelink** [comment]
Alright! Will be fixed for next version.
