### ISSUE TITLE
Sonar Analyzer MsBuild - sonar.cs.analyzer.projectOutPaths - No Protobuf files

### ISSUE THREAD

**Issue by TheGrussalo** [SonarSource/sonar-csharp#1205]
### Description

Upgraded SonarQube from 5.6.1 to 5.6.7 then to 6.7.1 on a test server.
Previous analysis used the Sonar Runner and I am now using the Sonar Analyzer for MsBuild.
Project has got the FxCop and StyleCop nuget packages added and when analysed it does not report any of the warnings.

### Plugins:
sonar-csharp-plugin-6.8.1.4648
sonar-javascript-plugin-4.1.0.6085
sonar-ldap-plugin-2.2.0.608

### Log file:
        18:02:33.540 INFO: 32 files indexed
        18:02:33.577 DEBUG: 'Generic Coverage Report' skipped because one of the required properties is missing
        18:02:33.704 WARN: Property missing: 'sonar.cs.analyzer.projectOutPaths'. No protobuf files will be loaded for this project.
        18:02:33.577 DEBUG: 'Generic Test Executions Report' skipped because one of the required properties is missing
        18:02:33.578 DEBUG: 'C# Tests Coverage Report Import' skipped because one of the required properties is missing
        18:02:33.578 DEBUG: '[Deprecated] C# Integration Tests Coverage Report Import' skipped because one of the required properties is missing
        18:02:33.578 DEBUG: 'C# Unit Test Results Import' skipped because one of the required properties is missing
        18:02:33.704 WARN: No roslyn issues report not found for this project.

Full log files (including MsBuild with diagnostics) has been uploaded to @valhristov Dropbox.

### Repro steps
        SonarQube.Scanner.MSBuild.exe begin /d:sonar.verbose=true /k:"*******.*****.NugetPackageManagement" /n:"******* ******* ****** Nuget Package Management" /v:"1.0" 
        "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild.exe" Denplan.ItOps.NugetPackageManagement.sln  /t:Rebuild
        SonarQube.Scanner.MSBuild.exe end

### Expected behavior

Project is analysed and FxCop and StyleCop errors appear in SonarQube.

### Actual behavior

Project is analysed but only Code Coverage issues were raised.

### Related information
Sonar-scanner-msbuild-4.0.2.892
MsBuild version 15.5.180.51428
SonarQube - 6.7.1

**Comment by valhristov** [comment]
Hi @TheGrussalo, Scanner for MSBuild will execute only analyzers that come from plugins installed on SonarQube. If you have other analyzers, you need to either wrap them into a plugin using the [Roslyn SDK](https://github.com/SonarSource/sonarqube-roslyn-sdk). As far as I know, there is already a FxCop plugin available, but I don't know of StyleCop plugin.

Are there any particular rules from FxCop you need that are not included in SonarC#? We put a lot of effort one year ago to implement the majority of the (useful) rules of FxCop in SonarC#.

**Comment by TheGrussalo** [comment]
Hi @valhristov, maybe my understanding is wrong.
When I build the project in Visual Studio 2017 the following errors appear:
![image](https://user-images.githubusercontent.com/8653115/36896346-36fa2cc2-1e0a-11e8-84c8-3125b88af3c7.png)
But in Sonar after analysing the only errors appear are Code Coverage:
![image](https://user-images.githubusercontent.com/8653115/36896471-bee6523c-1e0a-11e8-9b10-1b42cbd14418.png)

My understanding was that the FxCop plugin was for the Sonar Runner type analysis?

**Comment by valhristov** [comment]
Is your project [connected](https://www.sonarlint.org/visualstudio/howto.html#connected-mode) to SonarQube?

I can see that your SonarQube quality profile contains only 8 enabled rules and Scanner for MSBuild will execute only them. Visual Studio however, will execute the default quality profile (~200 rules) if your project is not connected. If it is connected, it will execute only rules enabled on SonarQube and you should see the same issues as Scanner for MSBuild generates (except those for code coverage and a few more, that are calculated on SonarQube).

I can see several issues reported by [S121](https://rules.sonarsource.com/csharp/RSPEC-121) in the MSBuild log, but they are in a test project and are not reported to SonarQube. We will be working on https://jira.sonarsource.com/browse/SONARMSBRU-281 and https://jira.sonarsource.com/browse/SONARMSBRU-345 in the near future and this limitation will disappear.

Regarding FxCop, not executing it is a side effect of running Scanner for MSBuild. The old Runner analyzed projects differently (in a less efficient manner) and executed all analyzers that were referenced in the project. The new Scanner disables the referenced analyzers and executes only those that were registered on SonarQube.

**Comment by TheGrussalo** [comment]
Thanks @valhristov, I think some of the issue was that my understanding was incorrect and that adding the analyzer to the .net solution would add the results to sonar.
We would like to (for now) implement the FxCop rules but I am struggling to do this.  I have tried creating an analyzer of FxCop using the [RoslynSonarQubeGenerator](https://github.com/SonarSource/sonarqube-roslyn-sdk) but this errroed stating that no analyzers were found.  I did find a defect for this but can't find it at the time of writing (the solution looked to be that a new parameter /recurse was going to be added to the RoslynSonarQubePluginGenerator.
How can I create a FxCop jar file?

**Comment by valhristov** [comment]
If you want to use just FxCop, there is a plugin already available here:
- https://github.com/DanielHWe/sonar-fxcop

You can also find it in the SonarQube Marketplace (login with admin, go to Administration -> Marketplace).

Regarding the Roslyn SDK problem, the best places to ask questions are either the [Google Groups](https://groups.google.com/forum/#!forum/sonarqube) or the [Roslyn SDK repository](https://github.com/SonarSource/sonarqube-roslyn-sdk) itself.

**Comment by TheGrussalo** [comment]
Thanks @valhristov.  I'm getting the impression that the best approach is to bin FxCop and StyleCop and just use the Sonar C# plugin moving forward and use the corresponding C# Analyzer within Visual Studio (linked to Sonar in connected mode).

**Comment by valhristov** [comment]
@TheGrussalo that would be the most friction-less approach for now.

**Comment by TheGrussalo** [comment]
@valhristov agreed, thank you for your help!

**Comment by Evangelink** [comment]
@TheGrussalo Just a side note. Feel free to open tickets for missing rules (from FxCop) that you think are valuable and we haven't implemented.

**Comment by Lexcess** [comment]
I get that you are interested in people using Sonarqube locally and on the server. I am a little hesitant, but mostly ok with you disabling the analyzers if the scanner is applied. However generating WARN messages generates noise in the build log and makes it seem like the developer did something wrong by adding a third party analyzer. That doesn't seem right.

For our devs it is not just a case of you adding the missing rules from StyleCop/FXCop and the other analyzers it is that those analyzers have really powerful fix options. Second some just don't want to add any cruft to the source tree as required by say SonarLint. Finally as long as the code meets the quality bar, we try not to be proscriptive about devs own local development process.

I hope you will make best effort to play nice with competitor analyzers on this one, especially as this is an introduced behaviour. Flashing red lights on a build if you don't go fully SonarQube doesn't feel like an act of good faith.
