### ISSUE TITLE
S3900: checking string parameter using string.IsNullOrWhitespace should not reported

### ISSUE THREAD

**Issue by fahadabdulaziz** [SonarSource/sonar-csharp#1216]
### Description

S3900 reports about parameter that should be checked before using it. though it reports about checking string parameter while its being checked using string.IsNullOrWhitespace.

### Repro steps

```csharp
public static string Pluralize(this string __phrase)
        {
            if (string.IsNullOrWhiteSpace(__phrase))
                throw new ArgumentNullException(nameof(__phrase));

            if(__phrase == "test")
                return "tests";

            return string.empty
}
```
### Expected behavior

Should not report shit situation 

### Actual behavior

Wrongfully reports string parameters

### Known workarounds

No workaround known..

### Related information

* SonarC# Version: 7.0.0.4787
* Visual Studio Version: 15.6.0

**Comment by michalb-sonar** [comment]
Thanks for reporting @fahadabdulaziz. We are aware of this problem, please observe issue https://github.com/SonarSource/sonar-csharp/issues/693

**Comment by fahadabdulaziz** [comment]
Thank you, hope it fixed
