### ISSUE TITLE
Version 7 is not available on nuget!

### ISSUE THREAD

**Issue by fahadabdulaziz** [SonarSource/sonar-csharp#1226]
Hi,

Last Monday you released version 7 of the analyzers, but now I can't find it.
https://www.nuget.org/packages/SonarAnalyzer.CSharp/

Thank you

**Comment by Evangelink** [comment]
Hi @fahadabdulaziz,

We have encountered some issues with the version 7.0.0 so we decided to remove the NuGet for now. We had to make a change to improve SonarLint for VS resulting in all rules being enabled by default.

Note that we are thinking about no longer publishing the NuGet analyzer as we want to provide a better user-experience and we cannot achieve what we want through this entry point.

**Comment by fahadabdulaziz** [comment]
Hi @Evangelink :-)

Is it going to be back?, if I may as what is SonarLint? 
I know it is a plugin for VS but will it show warnings in error list, and can I disable some of the analyzers or change the severity as I can do using the ruleset?

Thank  you
