### ISSUE TITLE
Sonar scanner not logging c# code issues in SonarQube

### ISSUE THREAD

**Issue by RamakantChandrakar** [SonarSource/sonar-csharp#1277]
### Description
i have a project it has  C#and javascript code visual stuod 2017 it has dotnet framework not using core,i installed sonar scanner sonar-scanner-msbuild-4.1.1.1164-net46, run sonar scanner on my project with command sonar-scanner, getting below error in console window
 " Property missing: 'sonar.cs.analyzer.projectOutPaths'. No protobuf files will be loaded for this project."

in Sonarqube 7.0  after analysis i am able to see  on top right corner its only perform analysis for javascript/xml code.even in error and bug list not able to find anything

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A

2. Step B

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

i want to see the code analyzed report for C# in sonarqube server 7.0

### Known workarounds

Please provide a description of any known workarounds.

### Related information

* SonarC# Version
* Visual Studio Version
* If running through the Scanner for MSBuild, its version

**Comment by valhristov** [comment]
Did you follow all the steps to analyze a .NET project?
https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+MSBuild

**Comment by RamakantChandrakar** [comment]
i run below command first part got success 
SonarScanner.MSBuild.exe begin /k:"Prep"

MSBuild.exe /t:Rebuild

SonarScanner.MSBuild.exe end

second part of command giving below error
The SonarQube MSBuild integration failed: SonarQube was unable to collect the required information about your projects.
Possible causes:
  1. The project has not been built - the project must be built in between the begin and end steps
  2. An unsupported version of MSBuild has been used to build the project. Currently MSBuild 14.0 upwards are supported
  3. The begin, build and end steps have not all been launched from the same folder
  4. None of the analyzed projects have a valid ProjectGuid and you have not used a solution (.sln)
sonar-project.properties files are not understood by the SonarScanner for MSBuild. Remove those files from the following folders: C:\2013Projects\PREP\PREP
19:14:32.544  Creating a summary markdown file...
19:14:32.56  Post-processing failed. Exit code: 1

**Comment by RamakantChandrakar** [comment]
followed the same step mention in above link

**Comment by valhristov** [comment]
Could you execute the following commands again:

```
SonarScanner.MSBuild.exe begin /k:"Prep" /d:sonar.verbose=true

MSBuild.exe /t:Rebuild /v:diag

SonarScanner.MSBuild.exe end
```

and upload the console logs and the zipped .sonarqube folder at:
https://www.dropbox.com/request/CszJAO1ZNXFVl1gwo5hA

**Comment by valhristov** [comment]
I am closing this ticket for now, please, write here again when you send us the execution logs.

**Comment by valhristov** [comment]
To be able to provide further help I would need the complete logs that were generated after the execution of the commands in my previous reply _and_ the zipped `.sonarqube` folder that is created in your project dir during the analysis.

**Comment by Evangelink** [comment]
Hi @RamakantChandrakar,

As asked by @valhristov we need the content of the `.sonarqube` folder to be able to debug more and so help you with your issue.

**Comment by RamakantChandrakar** [comment]
[.scannerwork.zip](https://github.com/SonarSource/sonar-csharp/files/1897363/default.scannerwork.zip)

please find attached sonarqube,scannerframework  folder form project and  logs that were generated after the execution

**Comment by Evangelink** [comment]
I was able to look at your logs. Can you confirm you are running the begin step before the build one? Also can you confirm you are running the begin and end steps from the same folder?

**Comment by RamakantChandrakar** [comment]
MSBuild.exe /t:Rebuild this command executed successfully then second command executed as SonarScanner.MSBuild.exe end and getting below error,please let me help is  missing something all log i  and project somarqube folder  shared with above conversation as .scannerwork.zip

Post-processing started.
The SonarQube MSBuild integration failed: SonarQube was unable to collect the required information about your projects.
Possible causes:
  1. The project has not been built - the project must be built in between the begin and end steps
  2. An unsupported version of MSBuild has been used to build the project. Currently MSBuild 14.0 upwards are supported
  3. The begin, build and end steps have not all been launched from the same folder
  4. None of the analyzed projects have a valid ProjectGuid and you have not used a solution (.sln)
sonar-project.properties files are not understood by the SonarScanner for MSBuild. Remove those files from the following folders: C:\2013Projects\PREP\PREP
10:55:40.321  Creating a summary markdown file...
10:55:40.364  Post-processing failed. Exit code: 1

**Comment by RamakantChandrakar** [comment]
also i tried below commands suggested by Valeri Hristov
1. SonarScanner.MSBuild.exe begin /k:"Prep" /d:sonar.verbose=true
2. MSBuild.exe /t:Rebuild /v:diag
3. SonarScanner.MSBuild.exe end
1 and 2 command executed successfully in 3rd command getting below error,please find the attached  log for same
[.sonarqube.zip](https://github.com/SonarSource/sonar-csharp/files/1901493/default.sonarqube.zip)

------------------------------------------------------------------------
sonar-project.properties files are not understood by the SonarScanner for MSBuild. Remove those files from the following folders: C:\2013Projects\PREP\PREP
10:57:10.081  Creating a summary markdown file...
10:57:10.086  Post-processing failed. Exit code: 1

**Comment by Bertk** [comment]
Please rename the file **"C:\2013Projects\PREP\PREP\sonar-project.properties"** and try again. 
MSBuild scanner uses a generated version of this file  ("**.sonarqube\out\sonar-project.properties**").

**Comment by Evangelink** [comment]
The `begin` and `end` steps of the Scanner for MSBuild must be run from the same folder and the folder should not contain any `sonar-project.properties` file.

For example you should do something like:
```
cd C:\2013Projects\PREP\PREP
SonarScanner.MSBuild.exe begin /k:prep
MSBuild.exe /t:rebuild
SonarScanner.MSBuild.exe end
```

Please let us know if it fixes your issue.

**Comment by RamakantChandrakar** [comment]
Thank  you guys 

SonarScanner.MSBuild.exe begin /k:"Prep" /d:sonar.verbose=true

MSBuild.exe /t:Rebuild /v:diag

SonarScanner.MSBuild.exe end 

and below suggestion it works
Please rename the file "C:\2013Projects\PREP\PREP\sonar-project.properties" and try again.
MSBuild scanner uses a generated version of this file (".sonarqube\out\sonar-project.properties").
