### ISSUE TITLE
Sonar fails with can't be indexed twice Error. Please check that inclusion/exclusion patterns produce disjoint sets for main and test files.Teamcity

### ISSUE THREAD

**Issue by MG12Coder** [SonarSource/sonar-csharp#1302]
Hi,
I am getting the same error while running the .net codebase build from teamcity.
[09:14:31][Step 2/2] Caused by: File [moduleKey=Bmpe_BmpeUiBaseOnlyKsorItem, relative=BMPECommunicationTest/App.xaml.cs, basedir=C:\BuildAgent\work\BWKsor] can't be indexed twice. Please check that inclusion/exclusion patterns produce disjoint sets for main and test files

I have setup two build steps for execution 1) msbuild 2) sonar runner on teamcity

These are the project sonar setting on my teamcity agent server
#edit these values accordingly
sonar.projectKey=com.rbs.mib:dotnet.BMPE
sonar.projectVersion=1.0
sonar.projectName=BMPE-BaseOnly-Ui
sonar.dotnet.visualstudio.solution.file=BMPE-BaseOnly.sln
sonar.dotnet.visualstudio.testProjectPattern=.Tests;.UnitTests
#end edit values

sonar.language=cs
sonar.sourceEncoding=UTF-8

sonar.ndeps.mode=skip
sonar.fxcop.mode=skip
sonar.stylecop.mode=skip
sonar.scm.enabled=true
sonar.skippedModules=BMPE.Tests,CommonControls,BMPE.DTO

and on teamcity where i have setup two build setup like below
![sonarstep1](https://user-images.githubusercontent.com/37796058/38183221-52b939de-365c-11e8-8d71-3b275b56ecc4.PNG)

![sonarstep2](https://user-images.githubusercontent.com/37796058/38183265-a635da54-365c-11e8-8bc1-5b99fbda305a.PNG)

can you please help me in this matter
what needs to be changed and where?

#Teamcity ; #SonarQube

**Comment by MG12Coder** [comment]
can anyone help?

**Comment by valhristov** [comment]
The Teamcity plugin is not developed by SonarSource and I cannot say what's exactly wrong. What I find suspicious is that you are using only one step for executing analysis on a .NET project, while two steps are required as per our documentation:
https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+MSBuild

I found this blog post that seems to cover what you need to do, please check it out and see if it helps:
https://maartenderaedemaeker.be/2017/07/22/setting-up-teamcity-sonarqube-integration-for-a-csharp-project/

**Comment by MG12Coder** [comment]
i have set two build step
1) Msbuild 2) SOnar Runner 
when i am running build from teamcity,i am getting this error which is only hurdle for me.
i am not getting why this error is coming,is it related to code or any mismatch configuration on teamcity.

**Comment by valhristov** [comment]
Ok, you need to have three step process: `SonarScanner.MSBuild begin`, `msbuild`, `SonarScanner.MSBuild end`. Otherwise it will not work for .NET projects.

**Comment by Evangelink** [comment]
@MG12Coder Are you still having any issue?

**Comment by Demetr** [comment]
Hello Evangelink,
I have exactly the same issue:
File can't be indexed twice
It appears after update of SonarQube server from 6.2 to 7.1
The SonarQube Runner for TeamCity is not updated.
Do you have any idea why I am getting those errors for C# and JS projects?

**Comment by Demetr** [comment]
Hello @agigleux,

Yes, I am using SonarQube 7.1 and Sonar CSharp 7.0.1.4822.

**Comment by Demetr** [comment]
Hello @valhristov 
Thank you for your suggestion.
I have fixed my issue via removing removing sonar.modules and sonar.inclusions and adding remaining folders to sonar.exclusions.

**Comment by Demetr** [comment]
Hello @valhristov ! You have advised avoiding using sonar.sources for .NET projects, hence I removed it and have got the error: 
[15:32:46][Step 5/5] ERROR: Caused by: You must define the following mandatory properties for 'App': sonar.sources
Could you possibly help how to fix that error then?

**Comment by valhristov** [comment]
Hi @Demetr, could you please share the commands you are executing and possibly the logs too? SonarScanner for MSBuild is setting the `sonar.sources` property internally and the error you are describing should not happen in normal circumstances.

**Comment by Demetr** [comment]
@valhristov, sonar-project.properties file and log of 2 TeamCity steps are attached
Thank you in advance!
[Log.txt](https://github.com/SonarSource/sonar-csharp/files/2072223/Log.txt)

**Comment by valhristov** [comment]
@Demetr I see your build is using the Team City's SonarQube Runner, which starts SonarScanner CLI, which in turn indeed requires `sonar.sources` to be specified.

The newer versions of SonarC# (since 6.0 if my memory is correct) do not support C# analysis through SonarScanner CLI and you need to use SonarScanner for MSBuild, which unfortunately does not seem to have a plugin for TeamCity. I think the easiest way to use SonarScanner for MSBuild with TeamCity is to [install it](https://docs.sonarqube.org/display/SCAN/Install+the+SonarScanner+for+MSBuild) on your build agent and run a script tasks before and after the actual build for the `begin` and the `end` steps of the analysis:
https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+MSBuild

**Comment by Demetr** [comment]
@valhristov, Thank you very much!
