### ISSUE TITLE
Issue with calling API via PowerShell using a token

### ISSUE THREAD

**Issue by Poseideon** [SonarSource/sonar-csharp#1308]
### Description

I have a simple PowerShell script in TFS 2017 that does a GET request to retrieve quality gate status for a given project. Since we have enabled AD authentication, the script fails with 401 Unauthorized error even after passing in the token in the request header.

The same token for the request works just fine when called via Curl command. Just won't work from PowerShell in TFS or SoapUI.

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A
Create a simple build definition in TFS 2017 and add an Inline PowerShell task. Paste below code and set the variables to your environment.

$projectkey = "$(ApplicationName)_$(Major).$(ReleaseDate)_DEVA"
$url = "$(SonarQubeQualityGateURL)" + '?projectKey=' + $projectkey 
$token = [System.Text.Encoding]::UTF8.GetBytes("$(SonarQubeUserToken)")
$base64 = [System.Convert]::ToBase64String($token)
$basicAuth = [string]::Format("Bearer:{0}", $base64)
$headers = @{ Authorization = $basicAuth }

$response= Invoke-RestMethod -Uri $url -Headers $headers 

2. Step B

Execute build

### Expected behavior

When a valid encoded token is passed, API must return a response.

### Actual behavior

getting a 401 Unauthorized error.

### Known workarounds

None

### Related information
SonarQube - 6.2
SonarC# - 6.6.0.3969
Visual Studio - 2017
If running through the Scanner for MSBuild, its version - SonarScanner for MSBuild 4.1.1

**Comment by Evangelink** [comment]
Hi @Poseideon,

Just to be sure I understand correctly. The problem appears when using powershell but is not related to the usage of the Scanner for MSBuild, isn't it?

**Comment by Poseideon** [comment]
Thanks for your response @Evangelink . I was able to resolve it by changing the authorization attribute to basic instead of Bearer and sending the token in place of username and leaving out the password.

$token = [System.Text.Encoding]::UTF8.GetBytes("$(SonarQubeUserToken)" + ":")
$base64 = [System.Convert]::ToBase64String($token)
$basicAuth = [string]::Format("Basic {0}", $base64)

**Comment by Evangelink** [comment]
Thanks for the update!

**Comment by marcusvnac** [comment]
Interesting, I am not being able to integrate TFS 2018 with SonarQube in a similar environment setup. The SonarQube TFS Integration within the Visual Studio Marketplace can have the same problem?

**Comment by Evangelink** [comment]
Hi @marcusvnac,

Please open a different issue and provide all the required information (listed when opening a new issue) so that we can provide a good answer.

Cheers,
Amaury

**Comment by marcusvnac** [comment]
Hey @Evangelink , I opened the issue 1716: https://github.com/SonarSource/sonar-csharp/issues/1716
