### ISSUE TITLE
Rule S2259: False positive on 'try/catch' with exception filter

### ISSUE THREAD

**Issue by ramondeklein** [SonarSource/sonar-csharp#1324]
### Description

Sonarqube raises a false positive when using try/catch-when.

### Repro steps
The following code raises an issue in the catch-body, because `webProxy` can be `null`. This can't happen, because the `when` ensures that the catch body is only executed when `webProxy` is not `null':

    var uri = new Uri("https://www.example.com");
    var webProxy = WebRequest.GetSystemWebProxy();
    var proxyUri = webProxy.GetProxy(uri);
    webProxy = proxyUri != uri && proxyUri != null ? new WebProxy(proxyUri) : null;
    try
    {
        Console.WriteLine($"{webProxy?.Credentials?.ToString() ?? "<no credentials>"}");
    }
    catch (WebException) when (webProxy != null)
    {
        webProxy.Credentials = new NetworkCredential("john.doe@example.com", new SecureString());
    }

### Expected behavior

SonarQube should also use the `when` clause expression.

### Known workarounds

The `when` keyword can be skipped and the code can be rewritten:

    try
    {
       ...
    }
    catch (Exception) when (obj != null)
    {
        obj.test = 0;
    }

as:

    try
    {
       ...
    }
    catch (Exception)
    {
        if (!(obj != null)) throw;
        obj.test = 0;
    }

This is functionally identical, but it introduces a rethrow.

### Related information

* SonarC# Version 6.7.1 (build 35068)
* Visual Studio Version: Visual Studio 2017 (15.6.6)

**Comment by Evangelink** [comment]
Hi @ramondeklein,

We have indeed a problem with this case. Thanks for reporting it!

Cheers,
Amaury
