### ISSUE TITLE
Drop the rule S3649

### ISSUE THREAD

**Issue by dbolkensteyn** [SonarSource/sonar-csharp#1386]
The following rule as currently implemented in SonarCSharp is generating too many false-positives:
* [RSPEC-3649](https://jira.sonarsource.com/browse/RSPEC-3649) SQL queries should not be vulnerable to injection attacks

It is about to be re-implemented using the taint analysis technique in SonarSecurity, for which we expect better results. However, because the same rule key will be re-used, it is a pre-requisite to first remove it from SonarCSharp prior to be able to ship SonarSecurity in SonarQube 7.2.

**Comment by agigleux** [comment]
It also means SonarC# 7.2 (the version match is a coincidence) must be released before SonarQube 7.2 so that SonarC# can be embedded into it without S3649.

**Comment by dbolkensteyn** [comment]
Of course @agigleux , and most importantly we need the UCFG producing code to be released as well

**Comment by Evangelink** [comment]
We will need to fix the `FIX ME` inside `CSharpSonarWayProfileTest.java` after this ticket is done.

**Comment by dbolkensteyn** [comment]
@Evangelink can you add a link to that `FIXME`? I don't see any in [CSharpSonarWayProfileTest.java](https://github.com/SonarSource/sonar-csharp/blob/master/sonar-csharp-plugin/src/test/java/org/sonar/plugins/csharp/CSharpSonarWayProfileTest.java) nor [CSharpSonarWayProfile.java](https://github.com/SonarSource/sonar-csharp/blob/master/sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSonarWayProfile.java)

**Comment by Evangelink** [comment]
@dbolkensteyn It's linked to @benzonico PR that's about to be merged.

**Comment by benzonico** [comment]
@Evangelink I would expect the `FIXME`  to be removed by dropping the rule.
