### ISSUE TITLE
Earlier I was using SONARQUBE 5.5 and sonar-csharp-plugin-5.0 which was having 407 C# Rules. But now i have upgraded to SonarQube 6.4 with which sonar-csharp-plugin-5.10.1.1411 comes by default and it has only 229 rules. I tried using the older version of SonarC# plugin but it is not compatible with this SonarQube version. Is there any way I can get all the C# Rules in SonarQube 6.4

### ISSUE THREAD

**Issue by sanyam42** [SonarSource/sonar-csharp#1408]
### Description

Please provide a succinct description of your issue.

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A

2. Step B

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

Please provide a description of the behavior you expect.

### Actual behavior

Please provide a description of the actual behavior you observe.

### Known workarounds

Please provide a description of any known workarounds.

### Related information

* SonarC# Version
* Visual Studio Version
* If running through the Scanner for MSBuild, its version

**Comment by Evangelink** [comment]
Hi @sanyam42,

Please when creating an issue try to keep a title with a reasonable length and use the description section to explain your issue. 

Also it is usually nice to post a small comment explaining why you are closing the issue. It helps us and other that might be in the same situation.
