### ISSUE TITLE
Option to delete roslyn report after scan

### ISSUE THREAD

**Issue by tao-zhang** [SonarSource/sonar-csharp#1410]
### Description

After scan, a *.Roslyn.json is created under each package. As I understand this is sonarqube scan report, and it will be uploaded to server eventually. My question is, is that possible to delete these reports locally?

### Expected behavior

Option or parameter to control if the scan report should be deleted after uploading to server.

### Actual behavior

No option to delete these scan reports.

### Known workarounds

No

### Related information

* SonarC# Version:  7.0.1 (build 4822)
* Visual Studio Version: MSBuild 15
* If running through the Scanner for MSBuild, its version: 4.0.2.892

**Comment by valhristov** [comment]
The *.Roslyn.json files are generated by the compiler and contain the output from all registered analyzers. SonarScanner for MSBuild is reading these files in its `end` step. You could delete them after that if you wish in an additional step in your build definition.

**Comment by tao-zhang** [comment]
@valhristov Thanks for the response. So that's not possible for SonarQube to delete those files.

**Comment by mc0re** [comment]
They also seem to be created upon `dotnet publish`, which looks wrong to me.

**Comment by pavel-mikula-sonarsource** [comment]
@mc0re We'd need more information about your scenario and pipeline and steps to understand your situation. Please refer to https://community.sonarsource.com and create thread there if you need help.
