### ISSUE TITLE
CSharp plugin does not shows any metric

### ISSUE THREAD

**Issue by sorgeas** [SonarSource/sonar-csharp#1428]
Hello,

I'm encountering issues very close to the one detailed in [https://github.com/SonarSource/sonar-csharp/issues/1102](https://github.com/SonarSource/sonar-csharp/issues/1102)

Here is my specific configuration:
1. Installed SonarQube 6.7 pointing on a blank database & setup the latest SonarC# plugin 7.1 (build 5212) + fxCop (1.3) & ReSharper (2.18) plugins
2. Performed a migration of my previous SonarQube 5.6 database
3. Recreated the quality profiles (exported from SonarQube 5.6 / imported in SonarQube 6.7)
4. Assigned an imported quality profile to projects (set as default)
5. Analyzed project

I end up with no C# lines of code in the analysis results, and the following logs from the runner (for each analyzed C# project):

`WARN: Analyzer working directory does not exist... Analyzer results won't be loaded from this directory.
`

Could you please advise? Is there a way to diagnose migration issues in dedicated logs?
Thanks for your help!

Sébastien

**Comment by valhristov** [comment]
Hi @sorgeas, do you use [Scanner for MSBuild](https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+MSBuild)? It is required to analyze with the later versions of Sonar C#.

**Comment by sorgeas** [comment]
Hi Valeri,

Actually I use the latest SonarQube extensions for TFS (4.2)

Sébastien

De : Valeri Hristov<mailto:notifications@github.com>
Envoyé le :lundi 28 mai 2018 10:43
À : SonarSource/sonar-csharp<mailto:sonar-csharp@noreply.github.com>
Cc : Orgeas, Sebastien<mailto:sebastien.orgeas@cgi.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [SonarSource/sonar-csharp] CSharp plugin does not shows any metric (#1428)


Hi @sorgeas<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sorgeas&d=DwMCaQ&c=H50I6Bh8SW87d_bXfZP_8g&r=uNV7zSBqu3FAToDFjEIMDb62gR2QannJT-w23mPetUc&m=G382kVl-lWz6pcI76nMQwgPdFScOuRk_8yQBy8ITNLM&s=gkFdLZYrJbJIaJbrBC5riYFsEUQNkRlT1fjjPydyobA&e=>, do you use Scanner for MSBuild<https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.sonarqube.org_display_SCAN_Analyzing-2Bwith-2BSonarQube-2BScanner-2Bfor-2BMSBuild&d=DwMCaQ&c=H50I6Bh8SW87d_bXfZP_8g&r=uNV7zSBqu3FAToDFjEIMDb62gR2QannJT-w23mPetUc&m=G382kVl-lWz6pcI76nMQwgPdFScOuRk_8yQBy8ITNLM&s=6SbXGsJ7EDT8Nkyb3SneTTW_DnopZgo5PHMitAoJF0U&e=>? It is required to analyze with the later versions of Sonar C#.

**Comment by valhristov** [comment]
Can you run the analysis with `sonar.verbose=true` and queue a new build with `Debug on` and send me the full logs?

**Comment by sorgeas** [comment]
Yes sure, is there any email address I can use to provide you the logs?

**Comment by valhristov** [comment]
You could drop the files here:
https://www.dropbox.com/request/CszJAO1ZNXFVl1gwo5hA

**Comment by sorgeas** [comment]
Logs have been uploaded :)

**Comment by valhristov** [comment]
Thanks for the logs @sorgeas. It seems that the SonarQube quality profile that you are using for this project does not contain C# rules. This could happen when migrating from older version of SonarQube. I cannot find the related ticket for SonarQube and I am not sure if this is going to be fixed soon, but in any case, I guess the easiest thing to do is to create new quality profiles and assign the rules again.

**Comment by sorgeas** [comment]
Thanks for your feedback @valhristov, that's exactly why I re-imported my quality profiles. I had also noticed that all the quality issues detected before migration are not visible anymore... is there a way to solve this without running new analyses?

**Comment by valhristov** [comment]
I don't think you could do it without messing with the database or analyzing everything again and I would not recommend the former :)

**Comment by sorgeas** [comment]
@valhristov I've created a brand new profile and activated the fxcop/ReSharper rules I'm interested in. Same result : no C# metrics generated. I've posted the logs on your dropbox.

**Comment by valhristov** [comment]
The message in the new logs is the same: `The exported profile does not contain a ruleset`. It is displayed when the SonarQube quality profile does not contain C# rules https://github.com/SonarSource/sonar-scanner-msbuild/blob/master/src/SonarScanner.MSBuild.PreProcessor/Roslyn/RoslynAnalyzerProvider.cs#L141.

Did you enable at least one Sonar C# rule in your new quality profile? We should probably change this, but Sonar C# will not generate metrics and other metadata (syntax highlight) if none of its rules are enabled.

**Comment by sorgeas** [comment]
The metrics are still not generated after activating Sonar C# rules on the new profile (neither with the imported one). So I will try to analyze again with a profile containing only Sonar C# rules.

Indeed I would vote for the enhancement you're suggesting 👍

**Comment by valhristov** [comment]
The quality profile seems to be OK now, but another file is not generated. I'll need some time to investigate.

**Comment by sorgeas** [comment]
@valhristov no I don't reference Microsoft.Net.Compilers nuget in this project, but the build agent is configured with Visual Studio 2015 Update 2 (not Update 3). I've tried on another agent having Visual Studio 2017 and the metrics are finally generated properly.

**Comment by valhristov** [comment]
Thanks for the update @sorgeas, let me know if you experience other problems with our analyzers.
