### ISSUE TITLE
The SonarQube MSBuild integration failed: SonarQube was unable to collect the required information about your projects.

### ISSUE THREAD

**Issue by aram000111** [SonarSource/sonar-csharp#1437]
### Description
Jenkins pipeline fails with SonarQube analysis.

### Repro steps
bat '''cd "%WORKSPACE%\\master"
      D:\\SonarMSBuild\\SonarScanner.MSBuild.exe begin /k:STAT /n:STAT /v:1.0 /d:sonar.verbose=true'''
bat '''cd "%WORKSPACE%\\master"
      "C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe" %WORKSPACE%\\master\\StateFilings.sln /t:Rebuild /p:Configuration=QA /p:OutputPath=obj\\QA /p:Platform=\"Any CPU\" /p:ProductVersion=1.0.0.${env.BUILD_NUMBER}'''
bat '''cd "%WORKSPACE%\\master"
      D:\\SonarMSBuild\\SonarScanner.MSBuild.exe end'''

[FullLog.txt](https://github.com/SonarSource/sonar-csharp/files/2066459/FullLog.txt)
SonarQube out file "ProjectInfo" has the following content:
Product projects
---------------------------------------

Test projects
---------------------------------------

Invalid projects
---------------------------------------
{none}

Skipped projects
---------------------------------------
{none}

Excluded projects
---------------------------------------
{none}

### Expected behavior
Successful Build
### Actual behavior
The SonarQube MSBuild integration failed: SonarQube was unable to collect the required information about your projects.
Possible causes:
  1. The project has not been built - the project must be built in between the begin and end steps
  2. An unsupported version of MSBuild has been used to build the project. Currently MSBuild 14.0 upwards are supported
  3. The begin, build and end steps have not all been launched from the same folder
  4. None of the analyzed projects have a valid ProjectGuid and you have not used a solution (.sln)

### Known workarounds

Please provide a description of any known workarounds.

**Comment by valhristov** [comment]
On line 18 in the build log there is a warning, that states the reason for the problem: `WARNING: Running the Scanner for MSBuild under Local System or Network Service account is not supported. Please, use a local or domain user account instead.`. This means that your build slaves run the Jenkins process using Local System account, which is not supported by SonarScanner for MSBuild. I would recommend creating a dedicated used for the build agents and run the Jenkins process with it.

**Comment by ChrisHimsworth** [comment]
I am using this on TeamCity using a Docker Agent, which is not domain joined and I haven't come across this issue. Since this change has been implemented we can no longer go beyond version 4.2.
Will there be an option to disable this behaviour?
