### ISSUE TITLE
Fix string formats in the csharp plugin

### ISSUE THREAD

**Issue by GeertvanHorrik** [SonarSource/sonar-csharp#1438]
See code at this line:

https://github.com/SonarSource/sonar-csharp/blob/05958f264b5c715c921f0b4c2e833b541f95cd7d/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/ProtobufImporter.java#L65

**Comment by Evangelink** [comment]
Hi @GeertvanHorrik,

Thanks for the feedback! I totally missed that one...
