### ISSUE TITLE
S107 should not raise for PInvoke methods

### ISSUE THREAD

**Issue by lukas-ais** [SonarSource/sonar-csharp#1459]
### Description

S107 should not raise for methods defined according external signature, like PInvoke methods.
Because the signature is defined externally the USE of the method should not get blamed.

### Repro steps

[DllImport("netapi32.dll", EntryPoint = "NetServerEnum")]
internal static extern int NetServerEnum([MarshalAs(UnmanagedType.LPWStr)] string servername, int level, out IntPtr bufptr, int prefmaxlen, ref int entriesread, ref int totalentries, SV_101_TYPES servertype, [MarshalAs(UnmanagedType.LPWStr)] string domain, int resume_handle);

### Expected behavior

Such methods (e.g. static extern or with DllImportAttribute) should be ignored while checking S107

### Actual behavior

The method gets S107 warning.

### Known workarounds

Using "pragma warning disable" the warning can be turned off locally.

### Related information

* SonarC# Version: 7.1.0.5212

**Comment by Evangelink** [comment]
Hi @lukas-ais,

Thanks for the feedback! You are absolutely right!

**Comment by lukas-ais** [comment]
Okay, I'll try to solve the problem.
Let's see if I can do this...

**Comment by lukas-ais** [comment]
With PR #1493 I fixed the issue, I think.
Should I close the ticket? Or are you doing? (Maybe it is required as marker for release notes or similar.)

**Comment by Evangelink** [comment]
That was a missed action on our side, thanks for the reminder!
