### ISSUE TITLE
S122 in VB.NET (Select case statement)

### ISSUE THREAD

**Issue by PanosKousidis** [SonarSource/sonar-csharp#1475]
Issue S122 keeps appearing in "Select Case" statements in VB.NET warning to reformat the code to have only one statement per line. This issue appears for all types of variables, booleans, strings, integers, everything.
I am attaching the enum case

![enum](https://user-images.githubusercontent.com/30468998/41458071-7f8ca4ea-707d-11e8-941a-7094c90e671b.png)

SonarQube: 5.6.1
Visual Studio: 15.7.2

**Comment by Evangelink** [comment]
Moved to https://jira.sonarsource.com/browse/SONARVB-266
