### ISSUE TITLE
S2583: string.IsNullOrWhiteSpace isn't correctly being checked

### ISSUE THREAD

**Issue by GeertvanHorrik** [SonarSource/sonar-csharp#1544]
### Description

See attached screenshot:

![image](https://user-images.githubusercontent.com/1246444/42471703-0187c6c4-83bf-11e8-9d91-24ddc426e89b.png)

In this case, the stringValue can be " ". This means that:

1. stringValue != null
2. string is string.IsNullOrWhiteSpace == true

### Repro steps

See attached screenshot.

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

This not to be a false positive.

### Actual behavior

False positive on string.IsNullOrWhiteSpace.

### Known workarounds

N/A.

### Related information

* SonarC# Version
* Visual Studio Version
* If running through the Scanner for MSBuild, its version

**Comment by valhristov** [comment]
Thanks for the feedback @GeertvanHorrik! This problem is caused by the same limitation of SonarC# that's described in #1347.
