### ISSUE TITLE
Feed metric 'executable_lines_data' when SQ >= 6.2

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonar-csharp#155]
As a replacement of the "force coverage to zero" feature, the plugin should provide for every executable file a measure that will tell platform what are executable lines (ie lines to cover by tests).

Note that the metric was introduced before 6.2 but due to an issue, measure should only be provided when runtime is 6.2+.

Contributes to [MMF-739](https://jira.sonarsource.com/browse/MMF-739)

**Comment by valhristov** [comment]
We need to mind the ExcludeFromCodeCoverage attribute and not report executable lines of code for that file (see related issue above)

**Comment by michalb-sonar** [comment]
Addressed by #873 #872 #871
