### ISSUE TITLE
Fix S4226: False positive for interfaces

### ISSUE THREAD

**Issue by MaxTranced** [SonarSource/sonar-csharp#1553]
### Description

> Extensions should be in separate namespaces.
> It makes little sense to create an extension method when it is possible to just add that method to the type itself.

However, adding a method is impossible when an interface is involved (at least for C# language versions prior to v8).

### Expected behavior

S4226 is not triggered for interfaces in language versions that don't support default method implementations.

### Known workarounds

N/A

### Related information

* SonarC# Version: 7.2 (build 5463)
* Visual Studio Version: 15.7.5
* If running through the Scanner for MSBuild, its version: 4.3.1.1372

**Comment by Evangelink** [comment]
Hi @MaxTranced,

Thanks for the feedback. We add a couple of discussions about this because we were not entirely sure where to go with this rule but at the end we decided to tweak the rule to allow extension methods on interface within the same namespace.

**Comment by MaxTranced** [comment]
Sounds good to me! 🙂

**Comment by andrei-epure-sonarsource** [comment]
Update: S4226 should only be reported for class extension methods. It should ignore interfaces, structs (which should be lightweight), enums (which cannot have methods) and generics.
