### ISSUE TITLE
sonarqube scanner for msbuild not creating output-cs folder

### ISSUE THREAD

**Issue by ReenaP-Hexaware** [SonarSource/sonar-csharp#1568]
### Description

Used Jenkins Sonarqube scanner forMSBuild plugin to scan C# files in the Dot Net Project.
Build gets success. But all metrics shown as 0 in Sonarqube server.
While checking the Jenkins build console found below warning and output-cs folder is not at all created in .sonarqube out folder.

INFO: -------------  Scan HW.HexaView.ConnectorAgents.Impl.Sonar
INFO: Load server rules
INFO: Load server rules (done) | time=265ms
INFO: Base dir: E:\JenkinsWorkspace\HexaViewNewArch\HW.HexaView.ConnectorAgents.Interfaces1\HW.HexaView.ConnectorAgents.Impl.Sonar
INFO: Working dir: E:\JenkinsWorkspace\HexaViewNewArch\.sonarqube\out\.sonar\hexarch_hexaviewarch_hexarch_hexaviewarch_532232B8-0269-451A-9C4E-A3466D88E2D2
INFO: Source paths: SonarQubeConnector.cs, Properties/AssemblyInfo.cs, SonarQubeObjects.cs
INFO: Source encoding: UTF-8, default locale: en_US
INFO: Index files
INFO: Included sources: 
INFO:   sonar.inclusions
INFO:   **/*.cs
INFO: 3 files indexed
INFO: 0 files ignored because of inclusion/exclusion patterns
INFO: Quality profile for cs: Sonar way
INFO: Sensor C# Properties [csharp]
WARNING: WARN: Analyzer working directory does not exist: 'E:\JenkinsWorkspace\HexaViewNewArch\.sonarqube\out\10\output-cs'. Analyzer results won't be loaded from this directory.
INFO: Sensor C# Properties [csharp] (done) | time=0ms
INFO: Sensor SonarJavaXmlFileSensor [java]
INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=0ms 

### Repro steps

Please provide the steps required to reproduce the problem

1. In Sonarqube server added sonar.inclusion as **/*.cs

2. Run the Jenkins build
[JenkinsLog.txt](https://github.com/SonarSource/sonar-csharp/files/2200307/JenkinsLog.txt)

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

Sonar analysis complete and Sonarqube server shows the metrics

### Actual behavior

Sonarqube reports shows 0 for all metrics

### Known workarounds

Please provide a description of any known workarounds.

### Related information

* SonarC# Version - 7.2 (build 5463)
* Visual Studio Version - 14.0
* If running through the Scanner for MSBuild, its version - MSBuild 14.0
SonarScanner for MSBuild verrsion - 4.0.2.892

**Comment by jarvars** [comment]
Similar #1570

**Comment by Evangelink** [comment]
Hi @ReenaP-Hexaware, @jarvars,

Reading your logs I have noticed that you are building using the `Microsoft.Net.Compilers.1.0.0` but if you read the release notes of the version [7.0 of SonarC#](https://github.com/SonarSource/sonar-csharp/releases/tag/7.0.0.4787) you will see a **Breaking Change Note** mentioning that from this version we will rely on Visual Studio 2015 Update 3 or greater which means Roslyn 1.3 or [Microsoft.Net.Compilers.1.3.2](https://www.nuget.org/packages/Microsoft.Net.Compilers/1.3.2).

Please either update the `Microsoft.Net.Compilers` NuGet version or rollback SonarC# to a version prior 7.0.

Let me know if this solves your issue.

Cheers,
Amaury

**Comment by jarvars** [comment]
I validated the MSBuild version and it does not correspond to the BuildTools of Visual Studio 2015 Update 3 , I updated and confirmed that the analysis is effective.
Thanks.

**Comment by Evangelink** [comment]
Alright cool!

**Comment by darshanapatel111** [comment]
I am getting the same issue but only with one project. result for another .csproj I am getting though. Can anyone suggest it?

**Comment by andrei-epure-sonarsource** [comment]
@darshanapatel111 as you have seen in this thread, to used the latest version of our analyzers you need to use Microsoft.Net.Compilers.1.3.2.
