### ISSUE TITLE
Fix S4457: False positive when throw of ArgumentException happens before first await

### ISSUE THREAD

**Issue by antoinebj** [SonarSource/sonar-csharp#1578]
### Description

I'm wondering why the non-compliant example in [RSPEC-4457](https://jira.sonarsource.com/browse/RSPEC-4457) is really non-compliant.
As far as I understand, `await DoSomethingAsync(); DoSomethingElse();` is a syntax shortcut for `return DoSomethingAsync().ContinueWith(t => DoSomethingElse());`.
So until the first await, nothing is wrapped in a continuation, and therefore exceptions get raised immediately without having to observe a task (because there isn't one yet).

If this issue is a mistake, perhaps the explanation could be added to the RSPEC?

### Repro steps

1. Create a class as such:

```csharp
public static class Incrementer
{
    public static async Task<int> IncrementAsync(int? value)
    {
        if (value == null)
        {
            throw new ArgumentNullException(nameof(value));
        }

        await Task.Delay(1000);

        return value.Value + 1;
    }
}
```

2. Add a call somewhere:

```csharp
var incrementTask = Incrementer.IncrementAsync(null);
```

### Expected behavior

As the exception happens immediately upon execution of the line in step 2, I suppose no violation of S4457 should be reported by Sonar.

### Actual behavior

A violation of S4457 is reported by Sonar.

### Related information

* SonarC# Version 7.3
* Visual Studio Version 15.7

**Comment by Evangelink** [comment]
Hi @antoinebj,

If you take your exact exemple you will notice that no `ArgumentNullException` is thrown. The exception will be thrown only when awaiting the task and most of the people don't expect this behavior (also when this happens in runtime and you are not using latest version of the framework it is really hard to debug).

```
class Program
{
    public static class Incrementer
    {
        public static async Task<int> IncrementAsync(int? value)
        {
            if (value == null)
            {
                throw new ArgumentNullException(nameof(value));
            }

            await Task.Delay(1000);

            return value.Value + 1;
        }
    }

    static void Main(string[] args)
    {
        var incrementTask = Incrementer.IncrementAsync(null); // No issue is raised here because the task isn't awaited
        var incrementTask2 = Incrementer.IncrementAsync(null); // Issue is raised here
    }
}
```

I agree that if you always await directly all async methods you are calling this rule is less critical. But keep in mind that you never know who will use your code so it is better to play defensive and assume that if the code is not awaited directly the exception will not be thrown from the expected location.

Browsing a bit the web you will notice that this pattern is often recommended and that Microsoft is using it internally.

FYI, there is a similar pattern for yielding methods: [RSPEC-4456](https://jira.sonarsource.com/browse/RSPEC-4456)

**Comment by antoinebj** [comment]
Indeed, I must have made the mistake of trusting the break on exception mechanism of Visual Studio.

It is a bit more clear with this slight enhancement:
```csharp
    class Program
    {
        public static class Incrementer
        {
            public static async Task<int> IncrementAsync(int? value)
            {
                if (value == null)
                {
                    throw new ArgumentNullException(nameof(value));
                }

                await Task.Delay(1000);

                return value.Value + 1;
            }
        }

        static void Main(string[] args)
        {
            try
            {
                Test();
                Debug.WriteLine("No problem!");
            }
            catch (Exception e)
            {
                Debug.WriteLine("Exception caught!" + Environment.NewLine + e);
            }
        }

        static void Test()
        {
            var incrementTask = Incrementer.IncrementAsync(null);
        }
    }
```

The output is "No problem!".
So contrary to what I said in the original comment, the async keyword on the method does force the wrapping of exceptions even before the first await call within the method. This actually makes sense because otherwise the developer would have to catch exceptions in 2 locations : around the call that gets the Task, and around the await (or as part of a continuation).

Sorry to have taken some of your time on this. Hopefully this issue will still be useful to other people who happen to be making the same mistake that I did.

**Comment by Evangelink** [comment]
You are welcome!

**Comment by StingyJack** [comment]
So to be clear the problem here is that in the example code there is a method declared as async (`IncrementAsync`) that is not being called with the `await` keyword or `.GetAwaiter().GetResuilt()` or `.Result` but is being used/observed later  via one of those or something like Task.WaitAll()?

If we call it in the normal style of using `await` as in `var result1 = await Incrementer.IncrementAsync(null);` we get the exception as expected at that point.  The former is not a terribly common practice from my experience.

Shouldnt this rule be evaluating the usages of the async function as well and reporting those as the problem and not guiding developers into breaking up Async as a Major code issue?
