### ISSUE TITLE
S1541 and null conditional operator

### ISSUE THREAD

**Issue by TPGEric** [SonarSource/sonar-csharp#1585]
With C#6 Null conditionnal operator, S1541 indicate a false positive, 
see code below 

![image](https://user-images.githubusercontent.com/33157150/43197178-a3dc240e-900a-11e8-87e7-eac59fab2bfc.png)

* SonarC# Version 7.2
* Visual Studio Version 2017 (15.7.5)
* If running through the Scanner for MSBuild, its version 4.3.1

**Comment by Evangelink** [comment]
Hi @TPGEric,

I am a bit surprised you consider this as FP as there is no strict definition of what the Cyclomatic Complexity should be doing regarding null coalescing operators (it was created for old code - when this kind of syntax didn't exist).

Are you comparing to some tool to consider this as a FP?

**Comment by TPGEric** [comment]
Hi, 
I did not compare with other tools. ..
Terminolgy "FP" is probably not adapted in this case, but how can we correct this state ?
Even if there is no strict definition for coalescing operator with CC, is it possible to ignore this kind of operator in this rule.

**Comment by Evangelink** [comment]
Hi,

Ok thank you the clarification. I'll discuss internally whether or not we want to improve Cyclomatic Complexity. FYI we have another rule, we think is more suitable for modern languages: https://rules.sonarsource.com/csharp/RSPEC-3776.

**Comment by Evangelink** [comment]
Hi @TPGEric,

We have reviewed the behavior of the rule and we do think this is the right behavior. This increments the count for each null-coalescing operator like it does for each ternary operator.

You can see the Cyclomatic Complexity as somehow the number of branches you have in your method. The null-coalescing being a syntax sugar for a if not null we do increase the count (i.e. you created one more branch).
