### ISSUE TITLE
Fix S1144: Unused private members should not report false positives with Unity classes

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonar-csharp#159]
We should investigate the options:
* whitelist affected classes, such as https://docs.unity3d.com/ScriptReference/MonoBehaviour.html, docs.unity3d.com/ScriptReference/AssetPostprocessor.html
* introduce a whitelist parameter which can be set by the user in SQ. Note that the list might be very long, (I'm not sure if there's a limit in SQ for parameter length), and that this rule should work out of the box with SonarLint with no parameters (at least for non Unity projects). 

See [SONARCS-677](https://jira.sonarsource.com/browse/SONARCS-677) for the full thread of discussion

**Comment by fmallet** [comment]
Suggested solution : no issue on a class extending MonoBehaviour, StateMachineBehaviour, AssetPostprocessor, AssetModificationProcessor, Editor, EditorWindow or ScriptableObject.

**Comment by valhristov** [comment]
StateMachineBehaviour, EditorWindow, Editor all derive from ScriptableObject and their descendants will be automatically excluded from raising issues from S1144.

**Comment by Bullrich** [comment]
Question about the fix for this issue, now, if a script inherits from a MonoBehaviour, it *will not report any* issue? Or only the not defined variables and unused methods issues will be ignored?

**Comment by costin-zaharia-sonarsource** [comment]
Hi @Bullrich 

Only [S1144](https://rules.sonarsource.com/csharp?search=1144) and [S4487](https://github.com/SonarSource/sonar-dotnet/issues/2686) are ignoring the classes which inherit from `MonoBehaviour`.

https://github.com/SonarSource/sonar-dotnet/blob/master/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs#L88

You can find here the complete list of types ignored by these two rules: https://github.com/SonarSource/sonar-dotnet/blob/master/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/UnusedPrivateMember.cs#L55

**Comment by lolgab** [comment]
Hi everyone :)
It seems that the same issue applies to https://rules.sonarsource.com/csharp/RSPEC-3052 . Is there any chance it can be `MonoBehaviour` can be allow-listed in that rule too?
