### ISSUE TITLE
Feed Cognitive Complexity metric

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonar-csharp#163]
Contributes to [MMF-733: Calculate Cognitive Complexity metric at file level and above](https://jira.sonarsource.com/browse/MMF-733)

**Comment by valhristov** [comment]
- [ ] upgrade protobuf file in java and .net projects
- [ ] fill the cognitive complexity messages in the .net projects
- [ ] read the cognitive complexity messages in the .net projects
