### ISSUE TITLE
No C# Analysis Being Show in SonarQube

### ISSUE THREAD

**Issue by jjferreira** [SonarSource/sonar-csharp#1685]
### Description

Im currently using Jenkins and SonarQube.

The code builds ok, and i seems to do some analysis.  Whoever when I got to SonarQube portal I get all sorts of analysis but not one for c#.

Please advise

### Expected behavior

Was expecting to see the c# analysis in the SonarQube portal.

### Actual behavior

I get analysis for XML, JS, and other but not c#.

### Related information

* SonarC# Version: 7.3.2 (build 6129)installed
* Visual Studio Version: 2015
* If running through the Scanner for MSBuild, its version ( Tried a few but right now trying 4.0.2.892 )

**Comment by Evangelink** [comment]
Hi @jjferreira,

Please do not cross-post here and on the [community forum](https://community.sonarsource.com/t/c-files-not-being-analyzed/1755). We will answer you on the community instance as your first post was there.
