### ISSUE TITLE
Update rule 'SHA-1 and Message-Digest should not be used' to include longer list

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonar-csharp#169]
DSA, HMAC-MD5, RIPEMD160, and HMACRIPEMD160 have been added to the specification for this rule.

Relates to [RSPEC-2070 SHA-1 and Message-Digest hash algorithms should not be used](https://jira.sonarsource.com/browse/RSPEC-2070)

**Comment by Evangelink** [comment]
This issue duplicates #149
