### ISSUE TITLE
SA1633 Should ignore generated files

### ISSUE THREAD

**Issue by orellabac** [SonarSource/sonar-csharp#1690]
### Description

I use some nugets which during the build process, generate some files. The files have the .generated.cs termination which is ignore on the SonarQ Server but locally an warning is reported.

### Repro steps

Please provide the steps required to reproduce the problem

1. Add a file like. Example.generated.cs

2. Add a header like:

#pragma warning disable
#line 1 "S:\\PBNetDCP\\src\\DCP\\Application.cs"

The pragma on the first line should disable any further analysis

### Expected behavior

No warning. Should be reported at all.

### Actual behavior

Warning    SA1633    The file header is missing or not located at the top of the file.    Project1.csproj    S:\src\Application.Hi5765hs.generated.cs    1    Active

### Known workarounds

No known workarounds

### Related information

* SonarC# Version using nuget SonarAnalyzer.CSharp version 7.3.0.5690
* Visual Studio Version 2017
* If running through the Scanner for MSBuild, its version

**Comment by valhristov** [comment]
Hi @orellabac, SA1633 is a StyleCop rule, it is not part of SonarC# and we cannot control its behavior.

We have a similar rule - [S1451](https://rules.sonarsource.com/csharp/RSPEC-1451), which does not raise issues on generated code. It's configuration is slightly different, though - you need to create an XML file, named `sonarlint.xml` and add it to your projects [like this](https://github.com/SonarSource/sonarlint-visualstudio/blob/master/src/SonarQube.Client/SonarQube.Client.csproj#L70). The `sonarlint.xml` content should be similar to [this file](https://github.com/SonarSource/sonar-scanner-msbuild/blob/master/SonarLint.xml). Then you could follow the instructions in the rule description to customize your file header.
