### ISSUE TITLE
S3433 TestMethodShouldHaveCorrectSignature does not handle all recognized test method types

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonar-csharp#1691]
S3433 does not recognize methods tagged with the following attributes as being test methods:
* _DataTestMethod_ (MSTest)
* _TheoryAttribute_ (Xunit , legacy and new)
* _TestCase_ (Nunit)
* _TestCaseSource_ (Nunit)
* _Theory_ (Nunit)

**Comment by Evangelink** [comment]
@duncanp-sonar `Type: Bug` is usually meant for something that crash. We have `Type: FP` and `Type: FN` for cases like this one.

**Comment by duncanp-sonar** [comment]
Fixed by #1704
