### ISSUE TITLE
S2360 "compliant solution" is not compliant

### ISSUE THREAD

**Issue by thomas76** [SonarSource/sonar-csharp#179]
The rule is "Optional parameters should not be used", yet the compliant solution contains an optional parameter:

_void Notify(string company, **string office = "QJZ"**)_

I assume it was erroneously copied from the noncompliant example.

**Comment by Evangelink** [comment]
Hi @thomas76!
Thanks for the feedback. We have just updated the subtask and we will make sure to ship this change in the next update.
