### ISSUE TITLE
Not all C# plugin ITs are being executed

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonar-csharp#1835]
Not all of the existing C# ITs are being run on CI because they are not included in the _TestSuite_.

See branch _run-all-its_.

Update: the following tests are failing on the server:
* SharedFilesTest.should_analyze_shared_files
* ScannerPluginCompatibilityTest.scanner_2_1_plugin_greater_than_6_should_fail_with_nice_message

**Comment by Evangelink** [comment]
Fixed by #1918
