### ISSUE TITLE
Not all C# ITs pass when run locally

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonar-csharp#1836]
Some of the ITs that pass on CIX do not pass when run on a local machine.

* AutoGeneratedTest => all
* CoverageTest: _no_coverage_on_tests_, _should_not_import_coverage_without_report_
* DoNotAnalyzeTestFilesTest => all
* MetricsTest => all except _filesAtProjectLevel_ and _linesAtProjectLevel_
* NoSonarTest => all

**Comment by Evangelink** [comment]
They are working when using a more recent version of the scanner for msbuild.
