### ISSUE TITLE
Update S2325: should not report methods in classes that inherit from System.Web.HttpApplication

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#1839]
### Description

The event handlers in `System.Web.HttpApplication` are automatically attached to the corresponding events if they follow certain naming convention and if they are static they don't work correctly.

Original community thread:
https://community.sonarsource.com/t/s2325-incorrectly-advises-global-asax-cs-application-xxx-methods-be-made-static/2386

**Comment by saciervo** [comment]
Hi @loic-joly-sonarsource 

I still get this rule reported by the analyzer. Despite having v7.10 installed. Could you please check on this?

Should be easy to reproduce on any MVC app. But you can use https://github.com/saciervo/sonar-repro-2325 to get a default MVC project with S2325 set to "Warning".

Kind Regards
Sandro

**Comment by Evangelink** [comment]
Hi @saciervo,

This is actually partially fixed! The case is handled but there is a [check about the declared accessibility](https://github.com/SonarSource/sonar-dotnet/blob/1fe5c476914113f298bb20cd22b523cf42deea14/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/MemberShouldBeStatic.cs#L171) that might be "wrong".
