### ISSUE TITLE
SonarLint for VS with TFS version control not usable

### ISSUE THREAD

**Issue by csoltenborn** [SonarSource/sonar-csharp#184]
SonarLint 2.11.0 for Visual Studio has severe problems with .ruleset files if TFS is used as the backing version control system (I assume that this is not an issue when using Git). The problems are described in detail in [this StackOverflow question](http://stackoverflow.com/questions/43113882/using-sonarlint-for-visual-studio-with-tfs-sharing-rulesets-accross-development).

**Comment by Evangelink** [comment]
Hi @csoltenborn,

I will close this issue and will let you recreate it into the [SonarLint for VS repository](https://github.com/SonarSource/sonarlint-visualstudio) as this repository is about the roslyn-based analyzers and the C# plugin.

We will then try to answer you as soon as possible.

Cheers,
DotNet Team

**Comment by csoltenborn** [comment]
Ok, sorry - note that the SonarLint homepage points to a deprecated GitHub repo which then points to this one, that's why I ended up here.

**Comment by Evangelink** [comment]
Thanks for letting us know that we have to update the SonarLint website links.
