### ISSUE TITLE
Random "can't be indexed twice" error

### ISSUE THREAD

**Issue by flonou** [SonarSource/sonar-csharp#1846]
### Description

We have a CI project with multiple steps and visual solutions and in one of those steps, we are sometimes having the error 
ERROR: Error during SonarQube Scanner execution
ERROR: File xxx.cs can't be indexed twice. Please check that inclusion/exclusion patterns produce disjoint sets for main and test files
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.

What's strange is that even when we do not change this visual solution at all, it sometimes works and sometimes fails. When it fails for a Merge request for example, it will fail no matter how many times we try to rerun the CI, when forcing the MR to be accepted, the CI will pass the step without any issue
It only happens with one visual solution, the other ones never exhibit such a problem
Also, I'm quite sure we do not have duplicates in our project.

### Repro steps

The commands in the CI are
```
'SonarScanner.MSBuild.exe begin /k:xxxxxxx /d:sonar.login=%sonar_token% /d:sonar.gitlab.url=https://xxxx /d:sonar.gitlab.project_id=%CI_PROJECT_ID% /d:sonar.gitlab.user_token=%fsqube_token% /d:sonar.gitlab.commit_sha=%CI_COMMIT_SHA% /d:sonar.gitlab.ref_name=%CI_COMMIT_REF_NAME% /d:sonar.analysis.mode="preview" /d:sonar.gitlab.only_issue_from_commit_line=true /d:sonar.gitlab.ping_user=true'
'msbuild xxxx.sln /t:Restore,ReBuild /p:Configuration=Release;Platform="Any CPU"'
'SonarScanner.MSBuild.exe end /d:sonar.login=%sonar_token%'
```

### Expected behavior

Either always fail or always succeed when building the same visual studio solution

### Actual behavior

Inconsistent error

### Known workarounds

Force the merge request to ignore the error

### Related information

* SonarC# Version : 7.4 (build 6452)
* Visual Studio Version : Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
* If running through the Scanner for MSBuild, its version : SonarScanner for MSBuild 4.2

**Comment by Evangelink** [comment]
Hi @flonou,

Could you try to update the version of the Scanner for MSBuild you are using? 
Would you be able to send me some small project where the error pops (frequently enough) so that I can debug? If you don't manage to create one, could you at least send me the `sonar-project.properties` file (located in the `.sonarqube` folder) when you have the failure happening?

**Comment by flonou** [comment]
Hi @Evangelink I will try to update the scanner first.
I'm not sure I can create a project where the error pops frequently enough, as I have no idea what is causing it. 
If the scanner update doesn't resolve the issue I will ask our IT service for the file you are asking for (I guess it's on the sonarqube server ?)

**Comment by Evangelink** [comment]
The `sonar-project.properties` of a failing build should be enough (I hope) for us to understand what's going on.

**Comment by flonou** [comment]
Updating the runner must have fixed our problem, the issue didn't occur since the update

**Comment by Evangelink** [comment]
Closing this issue then.
