### ISSUE TITLE
Fix S3457: should not report for Debug.WriteLine(message, category)

### ISSUE THREAD

**Issue by af4jm** [SonarSource/sonar-csharp#1851]
### Description

S3457 triggers a warning on a method call that does not have a format string, specifically `Debug.WriteLine(message, category)`.  The NuGet packages for the analyzers are not referenced anywhere in the solution.

### Repro steps

install SonarLint, code a call to `Debug.WriteLine(message, category)`

### Expected behavior

No warning

### Actual behavior

Bogus warning suggesting to delete the category

### Known workarounds

Uninstall SonarLint for VS

### Related information

* SonarC# Version 4.4.0.3745
* Visual Studio Version 15.8.3
* If running through the Scanner for MSBuild, its version

**Comment by valhristov** [comment]
It seems we need to improve our method resolution logic here, because we incorrectly detect the method call is for `Debug.WriteLine(string format, params object[] args)` instead of `Debug.WriteLine(string message, string category)`.
