### ISSUE TITLE
Cannot trigger S2931

### ISSUE THREAD

**Issue by lflender** [SonarSource/sonar-csharp#1854]
### Description

Unable to trigger S2931

### Repro steps

1. Activate S2931

2. Compile the non-compliant example provided in https://sonarcloud.io/coding_rules?open=csharpsquid%3AS2931&rule_key=csharpsquid%3AS2931

3. Look at warnings

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

Trigger S2931 when expected

### Actual behavior

Equivalent rule CA1001 is triggered but not S2931

### Known workarounds

Use the old CA1001 rule of the oudated FxCop legacy analyzer

### Related information

* SonarC# Version: 7.4 and 7.5
* Visual Studio Version: 2017
* If running through the Scanner for MSBuild, its version

**Comment by valhristov** [comment]
Hi @lflender, thanks for reporting this issue. Indeed, the rule does not seem to raise when executed in a project, even though its tests are passing. I suspect it is a timing issue and we will need to investigate further.
