### ISSUE TITLE
Fix S3928: Rule should not throw NullReferenceException for ArgumentNullException with null parameter name

### ISSUE THREAD

**Issue by nwoolls** [SonarSource/sonar-csharp#1867]
### Description

Running the SonarScanner on an .NET Core project that passes `null` to the `ArgumentNullException` constructor results in a `NullReferenceException` being logged by CSC.

### Repro steps

From a *nix environment:

1. Run `mkdir sonar-csharp-AD0001`
1. Run `cd sonar-csharp-AD0001`
1. Run `dotnet new console`
1. Edit the generated `.csproj` file and specify a `ProjectGuid`
1. Edit the generated `Program.cs` and add `throw new ArgumentNullException(null, String.Empty);`
1. Run `dotnet <path-to-scanner> begin [args]`
1. Run `dotnet build`
1. Run `dotnet <path-to-scanner> end [args]`

### Expected behavior

No warnings logged by CSC.

### Actual behavior

The following warning is found in the logs:

```
CSC : warning AD0001: Analyzer 'SonarAnalyzer.Rules.CSharp.CheckArgumentException' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [/Users/jdoe/src/tmp/sonar-csharp-AD0001/sonar-csharp-AD0001.csproj]
```

### Known workarounds

Don't pass `null` to `ArgumentNullException`, but this should probably be a rule not a difficult to track down `NullReferenceException`.

### Related information

* SonarC# Version: `7.5 (build 6605)`
* SonarScanner Version: `4.3.1`
* SonarQube Version: `6.7.1 (build 35068)`
* .NET Core SDK Version: `2.1.402`
* MSBuild Version: `15.4.0.0`

**Comment by Evangelink** [comment]
Hi @nwoolls,

Thanks for raising this issue!
It will be fixed on the next release.

Cheers,
Amaury
