### ISSUE TITLE
Fix S4261: rule should not report for MVC controller methods

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#1875]
### Description

Rule S4261 suggests method Xyz should renamed to XyzAsync if it is an async method. This rule should be suppressed for any public method on a class that derives from the MVC Controller base class, as this may interfere with routing.

Original request: https://community.sonarsource.com/t/s4261-methods-should-be-named-according-to-their-synchronicities-should-not-apply-to-controllers/2436

**Comment by paulhickman-a365** [comment]
It wouldn’t hurt to disable the rules for core/api controllers too, even if they do still work.

The reason for adding Async is so the developer writing the caller is aware of the synchronicity, but controller methods should not be called by developers, except for writing unit tests, so adding it doesn’t have the usual benefits.
