### ISSUE TITLE
Update install.ps1 to support newer Visual Studio 2017 versions

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#1876]
### Description

It seems that Visual Studio 2017 version 15.8.5 changed the project system to support adding analyzers and `install.ps1` and `uninstall.ps1` should take that into account. The new analyzer projects now contain the following code, that should be incorporated in our scripts:
```
if($project.Object.SupportsPackageDependencyResolution)
{
    if($project.Object.SupportsPackageDependencyResolution())
    {
        # Do not install analyzers via install.ps1, instead let the project system handle it.
        return
    }
}
```

### Related information

* SonarC# Version 7.5
* Visual Studio Version 15.8.5

**Comment by Evangelink** [comment]
Cannot reproduce.
