### ISSUE TITLE
Fix S4143: FN for Add called on 'this' or 'base'

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-csharp#1921]
### Description

S4143 does not raise issued when the `Add` method is called on `this` or `base`

### Expected behavior

    class InheritanceTest : Dictionary<int, int>
    {
        void InheritanceTest()
        {
            base.Add(0, 0); // Secondary
            base.Add(0, 1); // Noncompliant
        }
     }

### Actual behavior

    class InheritanceTest : Dictionary<int, int>
    {
        void InheritanceTest()
        {
            base.Add(0, 0); 
            base.Add(0, 1); // compliant
        }
     }

### Related information

* SonarC# Version 7.5

**Comment by valhristov** [comment]
There is already a test with this snippet that passes.
