### ISSUE TITLE
Prepare Analysis step on TFS fails with proxy

### ISSUE THREAD

**Issue by jeffpriz** [SonarSource/sonar-csharp#2011]
### Description

Build running on internal build server, attempting to run analysis reaching our SonarQube server on another machine, on the same subnet.  The Sonar Prepare Analysis step fails 
##[error][SQ] API GET '/api/server/version' failed, status code was: 503
When setting System.Debug = true on the build, evidence of it hitting the proxy server, and when I run wireshark I find that indeed it is routing to the proxy.  I've set the proxy settings on the server (and on the java control panel) to bypass the addresses however.. I don't understand how to make the sonar prepare step bypass the proxy server.

If I enter the url into a browser on the build server, it works with no issues.  If I run a build on an agent running on the same machine as the sonarqube server, there is no issue.  

I don't know how to make the sonarqube task bypass the proxy when attempting to communicate to the sonarqube server

### Repro steps

Please provide the steps required to reproduce the problem

1. Configure build def in TFS 2017 with the Sonar Prepare Analysis step, choosing the TFS Services Definition for our SonarQube server

2. Run build

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

The SonarQube analysis should run and connect to the sonarqube server

### Actual behavior

SonarQube traffic is being routed through the proxy, which is not valid for internal traffic.  Proxy settings on the build machine are set to bypass proxy for the address to the sonarqube server

**Comment by valhristov** [comment]
Hi @jeffpriz, the `begin` step of the scanner is executing .NET code, which should use the system-wide proxy configuration. The scanner should automatically bypass the proxy if it is configured in the Windows control panel. For more information, please check this article if you haven't read it yet:
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/proxy-configuration

**Comment by jeffpriz** [comment]
@valhristov  Yes, That is how I guess I expected it to handle the proxy settings, but that is not the behavior I am experiencing.  The Proxy settings are set on the server to bypass the proxy for that address that I am hitting, and when I use a browser i have no issues.. When the task runs during the build it does go to the proxy and fails..

**Comment by valhristov** [comment]
Hi @jeffpriz, since the analysis is executed on the agents, they are the ones that make the calls to the SonarQube server and you will have to configure the proxy settings on the agents themselves. I missed the part in your original question, where you said that it works on the server, but not on the agents...

I tested and the Windows version of the Scanner for MSBuild (it is included in the VSTS/TFS extension) correctly picks up the Windows Proxy Settings and exclusions.

**Comment by jeffpriz** [comment]
@valhristov Yes, the Agent - build machine, runs the Prepare task.. I have the proxy settings on that server set to bypass proxy for *.<mylocaldomain>.com  
When I access the sonarqube server at http://<mysonarmachinename>.<mylocaldomain>.com via the browser it works, and the WireShark results show it goes directly to the machine no troubles.

when the Sonar Prepare step runs, it get a 503 error, and the result from the proxy fails.. The WireShark results show that the traffic is routed to the proxy server..

**Comment by valhristov** [comment]
Ok, let's try something different then.

On the agent machine, find the folder:
`[BUILD AGENT ROOT]\_work\_tasks\SonarQubePrepare_15b84ca1-b62f-4a2a-a403-89b77a063157\[VERSION YOU USE HERE]\classic-sonar-scanner-msbuild`

create a text file named `SonarScanner.MSBuild.exe.config` and put the following content in it:
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <system.net>
    <defaultProxy enabled="false" />
  </system.net>
</configuration>
```

If you are using very old version of the VSTS/TFS extension it is possible that `SonarScanner.MSBuild.exe` does not exist and you will have to name the config file after the other executable: `SonarQube.Scanner.MSBuild.exe.config`.

If this works, I suggest checking if the agent's `machine.config` contains a `<defaultProxy>` section. It is possible that it is overriding the automatic proxy settings detection. Frankly speaking, I don't see other reason for the .NET `WebClient` not to pick up the Windows Proxy Settings...

**Comment by jeffpriz** [comment]
@valhristov  The Prepare step task ver 4.4.1 does not appear to have any .Net items.. The folder classic-sonar-scanner-msbuild does not exist..   

The sonar-scanner folder contains a bin and a lib folder.. the lib folder contains the JAR..  The node_modules folder contains, well node modules, and the common folder contains Javascript..

I believe the version of the task you are referencing is NOT the version I am using.. this is NOT a .Net item.  It's a Java task.. Which is why I was checking the Java control panel item to begin with.

**Comment by jeffpriz** [comment]
@valhristov  Well I don't believe that the part that is failing (the call to get /api/version) is happening in .net code..  I placed a .config in the folders as suggested..  I even tried placing specific bypass address information in the config file.. no change in behavior.. Just for fun I removed the two dotnet folders (dotnet-sonar-scanner-msbuild and classic-sonar-scanner-msbuild) all together.. and the task still runs, and still throws the same 503

**Comment by jeffpriz** [comment]
@valhristov I see what appears to be a call to the api/server/version in the javascript file @ common/helpers/request.js

**Comment by henryju** [comment]
@valhristov I created a ticket: https://jira.sonarsource.com/browse/VSTS-175 There is a workaround using request library environment variables.

**Comment by valhristov** [comment]
Thanks for looking into that @henryju!

@jeffpriz I think it is worth trying the workaround mentioned in the ticket above, it looks easy:
https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables

**Comment by jeffpriz** [comment]
AWESOME! Thanks. Adding NO_PROXY environment variables for the address worked! Thank you so much!

**Comment by DalpheSDC** [comment]
Remenber to restart the computer after adding the NO_PROXY
