### ISSUE TITLE
SonarC# - SharedProject doesn't work with sonarC# 

### ISSUE THREAD

**Issue by LGouellec** [SonarSource/sonar-csharp#2019]
Hi, 

When you have shared project in your solution, the analyser sonar C# doesn't work.
So, if you have a solution with a lot of shared projects, these indicates were wrong (too just one shared project ^^)

How do ?

Sincerely,

**Comment by duncanp-sonar** [comment]
Hi @LGouellec,

When creating an issue, please try to fill out the issue template to give us the information we need to be able to help you (e.g. SonarQube, SonarC# and Scanner for MSBuild version numbers).

You will need to use at least [version 6.7](https://github.com/SonarSource/sonar-csharp/releases/tag/6.7.0.4267) of the SonarC# analyzer together with [version 4](https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/4.0.2.892) of the Scanner for MSBuild to analyze shared files.
Issues on shared files should automatically be loaded to SonarQube; no additional configuration is required.

**Comment by LGouellec** [comment]
OK, thanks your for your answer.
