### ISSUE TITLE
Documentation Rule(s) Suggestion

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-csharp#2033]
Some users have suggested to add documentation related rules.

1. Ensure order of documentation tags. 

2. Ensure each tag is defined on a new line.

3. When a tag is present it should not be empty.

4. The `<param>` tag should be present for each parameter of the method

5. The `<returns>` tag should be present if the method has a return type.

6. The `<exception>` tag should list all exceptions explicitly thrown in the body of the method/property.

7. References to other classes, methods, properties... should be enclosed in a `<see>` tag.

8. A documentation must start with a capital letter and ends with a period.

9. Summary for the members should comply with a format.

- Constructors: `Creates a new instance....`
- Properties: `Gets...` or `Gets or sets...`
- Events: `Occurs when...`
- Method: should start with a verb

**Comment by Evangelink** [comment]
After an internal discussion we have decided not to implement these rules for the time being as we want to focus on rules active on the default quality profile (SonarWay).

Besides, starting with SonarQube 7.4, it is now possible to import into SonarQube issues from other Roslyn Analyzers. As such, it is now possible to use the [Documentation rules from StyleCope Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/DocumentationRules.md) which should cover most of the points raised previously.

**Comment by BlackAngelTiger** [comment]
Hello @Evangelink ,
i would love to see that rule provided by the SonarC# rules. I do not want to have a lot of analyzers of different companies in use. They all need to be configured, maintained and distributed for a lot of developers. This effort is not a good investment, if you already have SonarQube in use and want to get rid of the number of different tools use for code analysis.

Also SonarQube is a static code analyzer and the documentation of public interfaces is a part which should be integrated in a tool which clams to be a static code analyzer for the language C#.
