### ISSUE TITLE
Fix S3904 should not report in each file in the project

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#225]
Currently [S3904](https://jira.sonarsource.com/browse/RSPEC-3904) seems to report on each file in the C# project. It should be possible to report on a module level, e.g. on C# project level, without doing hacks.

The rule uses the following C# code to report and it is supposed to work fine:

    context.ReportDiagnostic(Diagnostic.Create(Rule, null));

We may need to experiment with different versions of SonarQube if this API changed, or a bug has appeared.

The following code (in the plugin) is supposed to correctly report on module level:

    newIssues.on(context.inputModule())

If the code above does not work, one of our options could be to report on the .csproj or some other arbitrary file if that's possible.

**Comment by Evangelink** [comment]
Cannot reproduce the issue with latest scanner of MSBuild used against SQ 5.6, 6.1, 6.2 and 6.4. (with msbuild 12 and 14).

**Comment by Evangelink** [comment]
User was using a deprecated scanner to analyze his files (see [here](https://stackoverflow.com/q/44439202/4625433)).
