### ISSUE TITLE
.dotnetcore/dotnetstandard  support

### ISSUE THREAD

**Issue by thgbrb** [SonarSource/sonar-csharp#227]
Hi Dear,

First, Congrats for all great work you have been doing! it is really amazing!
I would like to ask what is the roadmap to include the dotnetcore/dotnetstandard support.

thks and keep working :)

Best Regards,
Thiago

**Comment by Evangelink** [comment]
Hi @thgbrb! 

There are a couple of questions related to yours so to answer them all (we hope).

1. Is it possible to analyze dotnetcode/dotnetstandard with the Scanner for MSBuild? The answer is yes, the [last version (2.3)](https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/2.3.1.554) allows it.

2. Is it possible to do so on your TFS/VSTS agent? The answer is also yes using the [version 2.1](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube) of the sonarqube extension.

3. Is it possible with SonarLint for Visual Studio to use the connected mode with dotnetcore/dotnetstandard projects? The answer is no for now but we have planned to work on this soon.

4. Do we plan to move the codebase of our analyzers and of the Scanner for MSBuild to dotnetcore/dotnetstandard to enable cross-platform usage? The answer is yes but we cannot commit on any date for now.

We hope to have answered your questions.

Cheers,
DotNet Team
