### ISSUE TITLE
S1944 detects false Positive if casted to nullable 

### ISSUE THREAD

**Issue by Portikus** [SonarSource/sonar-csharp#228]
Hi everone,

I have the following code:

```csharp
public void TestMethod(object obj)
{
      var a = obj as MyClass;
      var test = (ushort?)a?.D;
      Console.WriteLine(test);
}

public class MyClass
{
   public double? D { get; set; } = 1.001;
}
```
The statement `(ushort?)a?.D;` causes a S1944 warning "Nullable is known to be empty, this cast throws an exception". But in my opinion this is a valid cast. if either the property D or the object a is null the cast works very well because it is cast to a nullable. Or am I wrong?

Greetings

**Comment by Evangelink** [comment]
Hi @Portikus !
Thanks for reporting this FP. We just merged a PR from a user that will fix it. Fix will be available in SonarC# 5.10.

Cheers
