### ISSUE TITLE
Do not import files detected as autogenerated in SonarQube

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#237]
We want to avoid the confusion in end users by preventing files that we detect as autogenerated from importing in SonarQube.

Use InputFileFilter to filter the not needed files.

Currently the C# and VB.NET analyzers consider files that match the following conditions as autogenerated:
- file name contains `".g."`, `".generated."`, etc.
- file has comment containing `"<auto-generated"` or `"<autogenerated"`
- file has any of these .NET attributes `"DebuggerNonUserCode"`, etc.
See [GeneratedCodeRecognizer.cs](https://github.com/SonarSource/sonar-csharp/blob/master/sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/GeneratedCodeRecognizer.cs) in SonarAnalyzer.sln for more information.

**Comment by jdcoffre** [comment]
In order help user understand why some files are skipped during the analysis, can we make sure that at debug level a log explicitly mentions the file name and the reason why it has been skipped. 

Thanks.
