### ISSUE TITLE
fxcop rules missing in 5.8 version

### ISSUE THREAD

**Issue by tijana88** [SonarSource/sonar-csharp#263]
### Description

After upgrade to  5.8 version of c# plugin there are no longer any FXCOP rules. Have they been removed for good? Is there a workaround to import these rules?

### Repro steps

Please provide the steps required to reproduce the problem

1. Upgrade from 5.3.2 to 5.8 

2. Go under Rules and FXCop rules that existe before no longer exist.

* SonarC# Version ->5.8
* Visual Studio Version
* If running through the Scanner for MSBuild, its version

**Comment by tijana88** [comment]
I'm sorry, please ignore this issue. I've found https://jira.sonarsource.com/browse/SONARCS-618?jql=project%20%3D%20SONARCS%20AND%20text%20~%20fxcop%20ORDER%20BY%20created%20DESC and https://github.com/SonarQubeCommunity/sonar-fxcop/releases. Once this plugin is also installed all rules are there.

**Comment by Evangelink** [comment]
HI @tijana88! Thanks for the self management of the ticket :)
