### ISSUE TITLE
Fix S2681: Rule should report on the correct line

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-csharp#264]
### Description
The issue is not reporting on the correct line. Besides, the block detection is also buggy and displays a -8 lines block instead of a 1 line block.

### Repro steps

Have a look at this issue on [SonarQube](https://sonarqube.com/issues#issues=AVu-iUbk2tKHZcediEhH)

### Expected behavior

Issue should be reported on line 625.

### Actual behavior

Issue is reported on line 617.

**Comment by valhristov** [comment]
Adding link to [RSPEC-2681](https://jira.sonarsource.com/browse/RSPEC-2681) for convenience.
