### ISSUE TITLE
Rule S101: Types should be named in camel case

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#273]
[RSPEC-101](https://jira.sonarsource.com/browse/RSPEC-101)

Shared naming conventions allow teams to collaborate efficiently. This rule checks whether or not type names are camel cased. To reduce noise, two consecutive upper case characters are allowed unless they form the whole type name. So, MyXClass is compliant, but XC on its own is not.

**Comment by valhristov** [comment]
Testing new script, disregard

**Comment by mihaivader** [comment]
Hello,

Thank you for the analyzer, really helpful.

Is there a way of adding exceptions to this rule?
For example, I would like that GMTService not fail this rule as "GMT" is a keyword which I want to ignore.

Thanks

**Comment by Evangelink** [comment]
Hi @mihaivader,

Thank you!
There is no such feature of exclusion list but depending on your usage, you can either:
- if paired with SonarQube/SonarCloud mark the issue as `False Positive` or `Won't Fix` on the server side
- if you are only using the analyzer, exclude the issue using a pragma

Cheers

**Comment by mihaivader** [comment]
Hi @Evangelink,

Thank you for the quick reply.
I had these 2 solutions in mind. I was just hopping for the ability to add some exceptions to the rule somewhere globally, rather than doing it using pragma on each specific case.

Any plans to support this sort of functionality in the future.

Cheers
