### ISSUE TITLE
Rule S3866: "IIf" should not be used

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#284]
[RSPEC-3866](https://jira.sonarsource.com/browse/RSPEC-3866)

Visual Basic .NET offers a non-short-circuit conditional, IIf(), which returns either its second or third parameter based on the expression in the first parameter. Using it is slower than using If() because each parameter is unconditionally evaluated. Further, its use can lead to runtime exceptions because IIf always evaluates all three of its arguments.

**Comment by Evangelink** [comment]
@valhristov Can you create the ticket for this one in Jira and close this one as duplicate?

**Comment by valhristov** [comment]
Duplicate with JIRA issue: https://jira.sonarsource.com/browse/SONARVB-241
