### ISSUE TITLE
Rule S3860: "ByVal" should not be used

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#285]
[RSPEC-3860](https://jira.sonarsource.com/browse/RSPEC-3860)

Since Visual Studio 2010 SP1, the ByVal parameter modifier is implicitly applied, and therefore not required anymore. Removing it from your source code will improve readability.

**Comment by Evangelink** [comment]
@valhristov Can you create the ticket for this one in Jira and close this one as duplicate?

**Comment by valhristov** [comment]
Duplicate with JIRA issue: https://jira.sonarsource.com/browse/SONARVB-240
