### ISSUE TITLE
Rule S3867: "CType" should be used for casting and explicit convertions

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#286]
[RSPEC-3867](https://jira.sonarsource.com/browse/RSPEC-3867)

For the sake of backward compatibility, Visual Basic .NET continues to offer a set of functions that convert from Object to different primitive types: CChar, CStr, CBool, CDate, CSng, CDbl, CDec, CByte, CSByte, CShort, CUShort, CInt, CUInt, CLng, CULng. However, using these functions is misleading, because it suggests a cast. It is better to cast explicitly using CType(), or use Convert.To() when the value should be converted.

**Comment by Evangelink** [comment]
@valhristov Can you create the ticket for this one in Jira and close this one as duplicate?

**Comment by valhristov** [comment]
Duplicate with JIRA issue: https://jira.sonarsource.com/browse/SONARVB-239
