### ISSUE TITLE
Sonar MSBuild: 'end' fails when filename contains a comma

### ISSUE THREAD

**Issue by tom-dudley** [SonarSource/sonar-csharp#329]
First off, apologies for posting here, but I can't make an issue for the `sonar-scanner-msbuild` project. Perhaps someone can move this issue.

The issue is that when running `SonarQube.Scanner.MSBuild.exe end` the scanner fails (hard) when hitting a file with a comma in it. It looks like this is because the source paths are comma delimited. Either ignoring the file or escaping the character (and handling that when reading the list) would fix this.

**Comment by Evangelink** [comment]
Hi @tom-dudley. 

Indeed this repository is meant for problems around the analyzers or the csharp plugin so your question doesn't belong here. The expected process for the Scanner for MSBuild is to create a thread on the Google Group or to ask a question on StackOverflow (see [here for guidelines](https://www.sonarqube.org/community/)).

Looking at Jira I have found [this ticket](https://jira.sonarsource.com/browse/SONARMSBRU-199) which relates to your question and that I invite you to upvote.
