### ISSUE TITLE
Rule S4016: Enumeration members should not be named "Reserved"

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#351]
[RSPEC-4016](https://jira.sonarsource.com/browse/RSPEC-4016)

If an enum members name contains the word "reserved" it implies it is not currently used and will be change in the future. However changing an enum member is a breaking change and can create significant problems. There is no need to reserve an enum member since a new member can be added in the future, this, usually, will not be a breaking change.

**Comment by IhnatKlimchuk** [comment]
@valhristov I've faced with this warning as I have an enum with actual "Reserved" value, aka "Reserved room". I'm extremely impressed that it was covered here. Also suggest to add "NotReserved", "IDK", "Blah", "BlackList", "WhiteList", "Slave", "Master", "Communism", "Montenegro" to this list. Have a great day! =)

**Comment by nicolas-harraudeau-sonarsource** [comment]
Hi @IhnatKlimchuk and thank you for your feedback.
We deprecated rule [S4016](https://jira.sonarsource.com/browse/RSPEC-4016) and specified [S6061](https://jira.sonarsource.com/browse/RSPEC-6061) instead which should avoid these kind of False Positives. There is no ETA as to when the new rule will be implemented. The old one will be removed from the default quality profile during the next release.

Next time could you please report False Positives, or any other suggestion, [on our community forum](https://community.sonarsource.com/)? Thanks!
