### ISSUE TITLE
Rule S4018: Generic methods should provide type parameters

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#353]
[RSPEC-4018](https://jira.sonarsource.com/browse/RSPEC-4018)

The best way to determine the type of generic method is by inference based on the type of arguments that is passed to the method. This is not possible when a parameter type is missing from the argument list.

**Comment by vamsitp** [comment]
Does this rule make sense when the return type is T (instead of void)?

**Comment by valhristov** [comment]
The rule is telling you that the compiler will not be able to infer the types of the method's generic arguments if there are no parameters of that type. If you only use the generic argument to specify return type you will have to always write it, which is fine in many cases. It should be safe to ignore the warning for such methods.

**Comment by JohnyWS** [comment]
Perhaps using the convention of [System.Func with naming the generic parameter "TReturn"](https://msdn.microsoft.com/en-us/library/bb534960(v=vs.110).aspx) would be a better alternative? I'd even argue that having that excemption in place would make it fine to increse the severity of the method again. :)
