### ISSUE TITLE
Rule S4021: "GC.KeepAlive" should not be called in a "SafeHandle"

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#355]
[RSPEC-4021](https://jira.sonarsource.com/browse/RSPEC-4021)

The SafeHandle class provides a simpler and safer way to manage the life cycle of objects. When converting to SafeHandle all call to GC.KeepAlive should be removed as they become unnecessary and could confuse a maintainer if left in the code.

**Comment by michalb-sonar** [comment]
Fxcop spec states that the rule applies to classes that use SafeHandle, but it's not clear how to determine the usage. Given the rule was has a low impact, it's not worth investigating it further at this point.

Note the fxcop implementation just loooks for the GC.KeepAlive call anywhere in the code, without checking for SafeHandle.

Closing as "won't fix".
