### ISSUE TITLE
Rule S2589: Should be a code smell but it's a bug

### ISSUE THREAD

**Issue by dee-see** [SonarSource/sonar-csharp#367]
### Description
According to [this code comment](https://github.com/SonarSource/sonar-csharp/blob/081828a0e58e50eb06aa0d346fb975d1be6faf74/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ConditionEvaluatesToConstant.cs#L50) and [this test](https://github.com/SonarSource/sonar-csharp/blob/abbe43eec6f001973c09661d9e2d3e132110219d/sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeTests.cs#L153) the rule S2589 should be a code smell, but as you can see [here](https://sonarqube.com/coding_rules#q=S2589) it's a bug, making it identical to rule 2583.

### Related information

SonarCSharp 5.10.1 (build 1411)

**Comment by valhristov** [comment]
Hi, sonarqube.com has not been updated with the new settings yet, hence some of the rules that should be code smell are still bugs. Unfortunately this is a manual operation and it is still pending in our todo list.
