### ISSUE TITLE
Fix S3897: Correctly recognize IEquatable<T> implementations from base classes

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#376]
Investigate why the following code is not compliant and provide a fix:

    class MyClass : IEquatable<MyClass> // Compliant
    {
        public override bool Equals(object obj)
        {
            return Equals(obj as MyClass);
        }
        public bool Equals(MyClass other)
        {
            return true;
        }
    }

    class SubClass : MyClass, IEquatable<SubClass> // Compliant?
    {
        public override bool Equals(object obj)
        {
            return Equals(obj as SubClass);
        }
        public bool Equals(SubClass other)
        {
            return true;
        }
    }

[Source](https://groups.google.com/forum/#!topic/sonarqube/t6WvagJ4rzw/discussion)

**Comment by overeemm** [comment]
I've attempted to fix this, but it isn't complete yet. https://github.com/SonarSource/sonar-csharp/pull/429

**Comment by Evangelink** [comment]
This is fixed by #464
