### ISSUE TITLE
SonarC# marked as deprecated in jira ?

### ISSUE THREAD

**Issue by doubret** [SonarSource/sonar-csharp#378]
Hello,
Just a quick question as we just introduced sonarc# in our company.

I saw in jira.sonarsource.com that the project was "deprecated" and would like to know the reason.

Is sonarc# going to be unmaintained ? Is there a better alternative ?

Thanks

**Comment by valhristov** [comment]
We decided that we will receive more feedback if we start using GitHub issues instead of Jira, hence we moved all Jira tickets here and deprecated the project. SonarC# is very much alive and kicking!

**Comment by doubret** [comment]
I found the jira here : https://jira.sonarsource.com/secure/BrowseProjects.jspa?selectedCategory=all

It looks like it changed from [DEPRECATED] to [MOVED TO GITHUB] between yesterday and today.

Thanks.

**Comment by valhristov** [comment]
We can't remove it from our Jira instance, but I hope the new prefix will prevent confusion in the future. Thanks for the feedback!
