### ISSUE TITLE
c# analyzes not working anymore after update to Sonar 5.6.6 LTS and SonarScanner 3.0.3

### ISSUE THREAD

**Issue by aumanjoa** [SonarSource/sonar-csharp#402]
### Description

We have used SonarQube in version 5.4 with the c# plugin 5.1 and the java sonar scanner. Indexing c# projects. 

Now we want to update to the new Sonar LTS version 5.6.6 using the newest java sonar.scanner and the newest c# plugin.  After doing this and running the analyses again on the project only 30% of the files are recognized as c# files in Sonar. 
This are the sonar.scanner files:

```
sonar.projectKey=test::test:Main
sonar.projectName=test_test_Main
sonar.projectVersion=7.4.0
sonar.scm.provider=tfvc

# Comma-separated paths to directories with sources (required)
sonar.sources=.

# Language
#sonar.language=cs

# Encoding of sources files
#sonar.sourceEncoding=UTF-8

#sonar.modules=
sonar.exclusions=**\\*.UnitTests\\**,**\\obj\\**,**\\Obj\\**,**\\tmp\\**,**\\XamlSnippets\\**,**\\bin\\**,**\\Bin\\**,**\\*_TypeInfo.cs,**\\ProductCatalog.cs,**\\HelperServiceBase.cs,**\\XmlManager.cs,**\\TaskCore.cs,**\\TaskProxy.cs,**\\ConfigurationManagerBase.cs,**\\ServiceConfigManager.cs,**\\WebConfigManager.cs
sonar.web.file.sufixes=.aspx,.html,.htm
sonar.xml.file.suffixes=.xaml,.wxs
sonar.cs.vscoveragexml.reportsPaths=..\\TestResults\\**\\*.coveragexml
sonar.cs.vstest.reportsPaths=..\\TestResults\\**\\*.trx
```

The result in sonar is that I see all the .cs files but only 30% are interpreted as c# files => have the syntax highlighting and sonar issues in the files.

If I run the build I see the "starting analyze" entry for every c# file

On the build machine, we have installed Visual Studio 2013. 

### Expected behavior

All c# files are interpreted by the c# plugin

### Actual behavior

Only about 30% of the files are interpreted 

### Related information

* SonarC# 5.6.6
* Visual Studio Version => 2013
* we are using the java scanner

**Comment by janos-ss** [comment]
It seems you're not using the SonarQube Scanner for MSBuild.

The recommended way of using SonarC# is documented on the [plugin's homepage](https://docs.sonarqube.org/pages/viewpage.action?pageId=1441900). 

- Were you aware of this recommendation?
- Would it be possible for you to start following this recommendation?
- Is there a reason to try to analyze your project without Scanner for MSBuild?

Note that when you use Scanner for MSBuild as recommended, you will not need the section at all that was in your request under "This are the sonar.scanner files". Scanner for MSBuild will automatically create the correct configuration based on your `.sln` and `.csproj` files.

I'm afraid we only support SonarC# when used with the Scanner for MSBuild.

**Comment by aumanjoa** [comment]
Hi @janos-ss 

Thanks for your quick reply.  

Please find here the answers to your question:

- Were you aware of this recommendation? => Yes but all internal scripts are optimized for the old Java Scanner
- Would it be possible for you to start following this recommendation? => Yes, but please see questions below
- Is there a reason to try to analyze your project without Scanner for MSBuild? => No

We have used the Java Scanner because of historical reasons, we are using SonarQube for a long time already where only the Java Scanner was available. So all internal scripts were already ready for the "old" Scanner. 

We are open to moving to the new MSBuild scanner. Doing this we have some questions:

1. What about Projects with multiple types of files needed to be analyzed? We are currently scanning projects which have c# code but also xml´s, Javascript code, Html,  ... which we want to analyze. Is the new MSBuild scanner capable of doing this, although the non-cs file types are not included in the csproj files?

2. In the current "sonar-project.properties" file we are grouping an amount of cs-projects together into logical Projects to become a better view instead of one long flat list of cs-projects. We are talking about 300+ projects. How can we achieve this with the new MSBuild scanner?

current part of the  sonar-project.properties:
`BuildProcess.sonar.projectName=BuildProcess
BuildProcess.sonar.projectBaseDir=BuildProcess\\Source
BuildProcess.sonar.sources=.

Portal.sonar.projectName=Portal
Portal.sonar.projectBaseDir=Portal\\Source
Portal.sonar.sources=.

Setup.sonar.projectName=Setup
Setup.sonar.projectBaseDir=Setup\\Source
Setup.sonar.sources=.

Deployment.sonar.projectName=Deployment
Deployment.sonar.projectBaseDir=Deployment\\Source
Deployment.sonar.sources=.
`

**Comment by henryju** [comment]
Hi @aumanjoa 

> What about Projects with multiple types of files needed to be analyzed? We are currently scanning projects which have c# code but also xml´s, Javascript code, Html, ... which we want to analyze. Is the new MSBuild scanner capable of doing this, although the non-cs file types are not included in the csproj files?

Nope, currently the Scanner for MSBuild will only analyze files listed in the .xxproj files. Is it common to have source files not listed in .xxproj?

> In the current "sonar-project.properties" file we are grouping an amount of cs-projects together into logical Projects to become a better view instead of one long flat list of cs-projects. We are talking about 300+ projects. How can we achieve this with the new MSBuild scanner?

I guess this is the precise use case for the Governance plugin: https://www.sonarsource.com/products/plugins/governance.html

**Comment by aumanjoa** [comment]
Hi,

we tried to migrate to the new msBuild scanner using our existing build proccess and we came across the following issue:
https://stackoverflow.com/questions/44702025/specify-the-working-directory-for-msbuild

Is there a solution for it? I guess it is solved in the TFS Scanner Plugin https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube

**Comment by janos-ss** [comment]
Closing this, because it seems the issue was resolved.
https://stackoverflow.com/a/44762567/641955
