### ISSUE TITLE
Using Shared project causes a lot of False positives

### ISSUE THREAD

**Issue by shadow-cs** [SonarSource/sonar-csharp#415]
### Description

When Shared project is used by multiple projects the analysis start to show a lot of false positives.

Rules that show false positives:
 * S3904
 * S3264
 * S1144 - Thought being used by a property or being a public property
 * S3459 - Though being assigned and used

Also when I fixed a suggestion by Sonar and rerun the analysis some issues were still present but did not show any source (there was none that it could show since I fixed it).

### Repro steps

1. Create a Shared project
2. Create two other projects that use the Shared project created in previous step (note that using one project will not trigger the issue)
3. Run the analyzer

[SonarIssues.zip](https://github.com/SonarSource/sonar-csharp/files/1064098/SonarIssues.zip)

Please note that not all these issues are presented in given sample project, if necessary I'll try to add them but since I think this is caused by the Shared projects not being properly supported this seems like unnecessary at this point. I think that the number of affected rules may grow as I just started using Sonar for a brand new project.

### Expected behavior

False positives are not detected.

### Actual behavior

False positives pile up.

### Known workarounds

None that I know of.

### Related information

* SonarC# 5.11
* Visual Studio 15.2
* Scanner for MSBuild 2.3.2

**Comment by Evangelink** [comment]
Hi @shadow-cs ! 

Thanks for reporting this issue. I need to run a bit more tests but from the tests I did our scanner doesn't properly supports shared projects that's why you are experiencing these issues. It is surprising than no-one ever reported this issue before.

**Comment by Evangelink** [comment]
Move issue to the right project and close this one.

Please continue discussion on JIRA ticket [SONARMSBRU-331](https://jira.sonarsource.com/browse/SONARMSBRU-331).
