### ISSUE TITLE
Do not skip source files that contains "ExcludeFromCodeCoverage*" attributes 

### ISSUE THREAD

**Issue by jdcoffre** [SonarSource/sonar-csharp#428]
### Description

If a source file contains "ExcludeFromCodeCoverage" or "ExcludeFromCodeCoverageAttribute" code attribute, the analyzer will skip the file from the analysis.

This mechanism has been put in place the prevent SonarC# to analyze generated source code. This codding attributes are not related to auto-generated code. 

The aim of this issue to prevent the analyzer to skip any source file relying on these coding attributes.
[Here](https://github.com/SonarSource/sonaranalyzer-dotnet/blob/master/src/SonarAnalyzer.Common/Helpers/GeneratedCodeRecognizer.cs#L56,L57) is the related source code.

### Repro steps

 - create a project
 - 2 source files of this project respectively uses code attribute  "ExcludeFromCodeCoverage" or "ExcludeFromCodeCoverageAttribute"
 - run the analysis
 - confirm that the files are skipped

### Related information
It impact any analysis since version 5.4 of SonarC#.

**Comment by valhristov** [comment]
Related issue #155

**Comment by TheEngineeringAlgorist** [comment]
Why wouldn't you want to skip a file that is telling you to skip it?

**Comment by andrei-epure-sonarsource** [comment]
It's saying to exclude the file from code coverage, not from static code analysis, right?

**Comment by DanielHWe** [comment]
It would be fine if they are still scanned, but thay are listed to be not covered by unit tests. I did only mark some methods/Properties to not be exclued from code coverage but sonar still say they need to be covered.

**Comment by pavel-mikula-sonarsource** [comment]
Hi @DanielHWe, this issue was closed 2 years ago.

Please create a new topic on https://community.sonarsource.com with full description of your scenario that could help to understand the situation.

Thank you
