### ISSUE TITLE
Fix S2259: "Null pointer dereference" raises FP when a variable is initialized in catch(Exception) block

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#493]
```
object o = null;
try
{
    o = new object();
    // do something
}
catch
{
    o = new object();
}
return o.ToString(); // FP is detected
```

TIP: The CFG has connection between the beginning of the try block and its end for the cases when a potential exception is not caught. However, catch or catch(Exception) will catch all exceptions, meaning that the connection is not needed in this case.

**Comment by michalb-sonar** [comment]
This should fix these FPs:
https://peach.sonarsource.com/project/issues?id=akka&open=AVzkyPyGyCkvGIDnupYu&resolved=false&sinceLeakPeriod=true&types=BUG
https://peach.sonarsource.com/project/issues?id=jabbr&open=AVzktMudyCkvGIDnupYQ&resolved=false&sinceLeakPeriod=true&types=BUG
https://peach.sonarsource.com/project/issues?id=lucene&open=AVzkvebtyCkvGIDnupYe&resolved=false&sinceLeakPeriod=true&types=BUG
https://peach.sonarsource.com/project/issues?id=roslyn-commit&open=AVzk8H1OyCkvGIDnupaB&resolved=false&sinceLeakPeriod=true&types=BUG
https://peach.sonarsource.com/project/issues?id=monogame&open=AVzkwsueyCkvGIDnupYn&resolved=false&sinceLeakPeriod=true&types=BUG
