### ISSUE TITLE
Fix S2234: Check for parameter types before reporting it as bug

### ISSUE THREAD

**Issue by ThyPillow** [SonarSource/sonar-csharp#496]
### Description

Currently rule [S2234](https://jira.sonarsource.com/browse/RSPEC-2234) - Parameters should be passed in the correct order - checks the name of the parameters but not their type.  Consider the following method signature

        void Do(DateTime date, CustomTimeType time)

Calling it with inverted parameters name is currently treated as Bug, but caller code wouldn't compile if it was. At most it would be a minor CodeSmell.

### Expected behavior

Calling it with inverted parameters name should not report an error due to type unassignability.

### Actual behavior

Detected as a Bug with default severity Major.

**Comment by Evangelink** [comment]
Hi @ThyPillow,

Thanks for this feedback. 
Indeed, the `Bug` classification seems a big hard (I will discuss this with the team). Regarding the type check this is also a pretty good point (same output I will discuss this with the team).
