### ISSUE TITLE
Rule S110: "filteredClasses" documentation should describe which delimiter to use or provide specific examples

### ISSUE THREAD

**Issue by RalfKoban** [SonarSource/sonar-csharp#519]
Hi,

The rule S110 "Avoid excessive inheritance provides a parameter called "filteredClasses" (http://www.sonarlint.org/visualstudio/rules/index.html#version=6.0.0.2033&ruleId=S110).

The description for that parameter should list the delimiter to use in case someone wants to provide some filters. In addition it should be mentioned whether those strings are only the class names or shall be the full names incl. the namespaces.

* SonarC# Version: 6.0.0.2033
* Visual Studio Version: Irrelevant - it's about documentation
* If running through the Scanner for MSBuild, its version: Irrelevant - it's about documentation

Best regards,
Ralf Koban

**Comment by Evangelink** [comment]
Hi @RalfKoban,

Thanks for the feedback. We will make sure to update the documentation for the 6.2 release.
