### ISSUE TITLE
Fix S101: "Class Name" infinite loop when class name contains non-Latin Characters

### ISSUE THREAD

**Issue by czphoenix** [SonarSource/sonar-csharp#526]
### Description

There will be a infinite loop in 
File: [SonarAnalyzer.CSharp/Rules/ClassName.cs](https://github.com/SonarSource/sonar-csharp/blob/master/sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/ClassName.cs) 
Class: internal class CamelCaseConverter
Method: public static string Convert(string identifierName)
When
char.IsLower(suggestion[currentIndex]) 
char.IsNumber(suggestion[currentIndex])
char.IsUpper(suggestion[currentIndex])
all return false

### Repro steps

1. Create a project with a class named in non-Latin characters. e.g. Chinese which is fine in C#.
class 你好{}

2. Run.

### Expected behavior

Finish when done.

### Actual behavior

Runs forever with high CPU usage.

### Known workarounds

Use all Latin characters in class name.

### Related information

* SonarC# Version: 6.0.0.2033
* Visual Studio Version: 2017
* If running through the Scanner for MSBuild, its version: MSBuild15

**Comment by valhristov** [comment]
Hi @czphoenix,

Thanks for the bug report, and don't hesitate to send us more, we appreciate it!

Valeri
