### ISSUE TITLE
SonarAnalyzer assembly version 6.1.0.0 is not deployed with SonarLint Visual Studio extension

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [SonarSource/sonar-csharp#546]
### Description

SonarAnalyzer.CSharp.dll version 6.1.0.0 assembly has a dependency on SonarAnalyzer.dll 6.1.0.0, **which is not deployed**. There is 6.0.0.0 version of SonarAnalyzer.dll, but it cannot be loaded for obvious reason (Wrong version, duh!).

### Repro steps

1. Launch Visual Studio 2015

2. Create a new C# console application project

3. Wait for "Error List" window to fill up with warnings

### Expected behavior

It should start analyzing project right away.

### Actual behavior

Hundreds of warnings are generated in "Error List" window. Here is an example:

```
Warning	AD1000	An instance of analyzer SonarAnalyzer.Rules.CSharp.DelegateSubtraction cannot be created from C:\USERS\ADMINISTRATOR\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\VF300HN1.EC5\SonarAnalyzer.CSharp.dll: Could not load file or assembly 'SonarAnalyzer, Version=6.1.0.0, Culture=neutral, PublicKeyToken=c5b62af9de6d7244' or one of its dependencies. The system cannot find the file specified..			1	Active	Could not load file or assembly 'SonarAnalyzer, Version=6.1.0.0, Culture=neutral, PublicKeyToken=c5b62af9de6d7244' or one of its dependencies. The system cannot find the file specified.
-----
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

-----
```

After turning on Fusion log as warning message suggests:

```
Warning	AD1000	An instance of analyzer SonarAnalyzer.Rules.CSharp.GetHashCodeEqualsOverride cannot be created from C:\USERS\ADMINISTRATOR\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\VF300HN1.EC5\SonarAnalyzer.CSharp.dll: Could not load file or assembly 'SonarAnalyzer, Version=6.1.0.0, Culture=neutral, PublicKeyToken=c5b62af9de6d7244' or one of its dependencies. The system cannot find the file specified..			1	Active	Could not load file or assembly 'SonarAnalyzer, Version=6.1.0.0, Culture=neutral, PublicKeyToken=c5b62af9de6d7244' or one of its dependencies. The system cannot find the file specified.
-----
=== Pre-bind state information ===
LOG: DisplayName = SonarAnalyzer, Version=6.1.0.0, Culture=neutral, PublicKeyToken=c5b62af9de6d7244
 (Fully-specified)
LOG: Appbase = file:///C:/Visual Studio 14/Common7/IDE/
LOG: Initial PrivatePath = NULL
Calling assembly : SonarAnalyzer.CSharp, Version=6.1.0.0, Culture=neutral, PublicKeyToken=c5b62af9de6d7244.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Users\Administrator\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: The same bind was seen before, and was failed with hr = 0x80070002.

-----
```

(Analyzer rule name is not relevant here, this error is selected randomly from list of hundreds).

After exploring `C:\USERS\ADMINISTRATOR\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\VF300HN1.EC5\` directory contents, it became clear, that `SonarAnalyzer.CSharp, Version=6.1.0.0` assembly is trying to load `SonarAnalyzer, Version=6.1.0.0` assembly, but cannot locate it by this identity. There is `SonarAnalyzer, Version=6.0.0.0` assembly in this directory, which seems to be older version and cannot be loaded.

### Known workarounds

You can add assembly binding redirect to `devenv.exe.config` file to redirect 6.1.0.0 to 6.0.0.0:

```
<dependentAssembly>
    <assemblyIdentity name="SonarAnalyzer" publicKeyToken="c5b62af9de6d7244" culture="neutral"/>
    <bindingRedirect oldVersion="6.1.0.0-9.0.0.0" newVersion="6.0.0.0"/>
</dependentAssembly>
```

But this resolves problem only partially and introduces yet another problem: quite a large number of analyzer rules will start throwing `MissingMethodException`.

### Related information

* SonarLint `3.2.0.1601`
* Visual Studio 2015 `14.0.25431.01 Update 3`
* .NET Framework `4.7.02053`
* SonarLint.dll assembly identity: `SonarLint, Version=3.2.0.0, Culture=neutral, PublicKeyToken=c5b62af9de6d7244`
  `"Version:3.2.0.1601 Branch:master Sha1:30fa576c6f60c3fd2230119b9b686a810bdbbb36"`
* SonarAnalyzer.dll assembly identity: `SonarAnalyzer, Version=6.0.0.0, Culture=neutral, PublicKeyToken=c5b62af9de6d7244`
  `"Version:6.0.0.2033 Branch:master Sha1:f3066b8f90d0b455581729c9fb9305a25a04fe9a"`
* SonarAnalyzer.CSharp.dll assembly identity: `SonarAnalyzer.CSharp, Version=6.1.0.0, Culture=neutral, PublicKeyToken=c5b62af9de6d7244`
  `"Version:6.1.0.2359 Branch:master Sha1:e424d9e59788fb894c100d9a7328b2a991b79bcc"`

**Comment by valhristov** [comment]
Hi @0xfeeddeadbeef, 

Thanks for the bug report, we already published a new version of SonarLint, you can update now.

All the best,
Valeri

**Comment by Evangelink** [comment]
Close and link issue from the right repository (also as mentioned by @valhristov the bug fix is released).
https://github.com/SonarSource/sonarlint-visualstudio/issues/219
