### ISSUE TITLE
Fix S3908: Rule should not report issues on classes that implement interfaces

### ISSUE THREAD

**Issue by RalfKoban** [SonarSource/sonar-csharp#550]
Hello,

I have some classes that implement a specific interface ( System.Windows.Input.ICommand ). That ICommand defines an event of following signature:

            event EventHandler CanExecuteChanged;

As my class implements that interface, I have to implement that event as well.
However, Sonar reports that as an issue.

### Repro steps

Create a C# project and a class that implements the  System.Windows.Input.ICommand interface.

### Expected behavior

Rule S3908 is not violated.

### Actual behavior

Error window contains an entry that rule 3908 is violated.

### Known workarounds

Disable/suppress the rule temporarily

### Related information
* SonarLint for Visual Studio 2017 Version 3.2.1.1639
* Visual Studio Enterprise 2017 Version 15.2 (26430.15) Release

**Comment by valhristov** [comment]
Hi @RalfKoban, thanks for the suggestion, we think it is reasonable and we will implement it in an upcoming sprint. Please, don't hesitate to send more feedback!

**Comment by Evangelink** [comment]
There are actually 2 FP raised here:
- `EventHandler` type is not allowed (but should be)
- When implementing/overriding a delegate event, rule should not raise an issue
