### ISSUE TITLE
S110: Adding filters will mark all issues as Closed ('Fixed')

### ISSUE THREAD

**Issue by KevinSchiener** [SonarSource/sonar-csharp#552]
### Description

Since the rule doesn't differentiate between framework code and our custom code we get hundreds of false positives, especially on WPF related code. I could remedy this by adding filters in the form of `System.Windows.*` to the rules filteredClasses property.

The downside is that all the issues that were created before are now closed as fixed and not as removed. We use the leak period get an overview over which issues actually get fixed. These falsely fixed ones now make that quite hard.

### Repro steps

1. Run sonarqube c# on any WPF project with custom controls and get loads of S110 violations since WPF uses deep hierarchies
2. Change the filteredClasses property on S110 to `System.Windows.*`
3. Wait for the next analysis

### Expected behavior

All filtered issues are now marked as _Closed (fixed)_.

### Actual behavior

Issues should be marked as _Closed (removed)_

### Known workarounds

I'd be happy for a workaround or any indication on how to remove these issues.

### Related information

* SonarC# Version: 5.10.1 (build 1411)

**Comment by Evangelink** [comment]
Hi @KevinSchiener,

Thanks for your feedback. Unfortunately there is no way currently (not even an hacky one) for you to remove the issues but we do have [a ticket](https://jira.sonarsource.com/browse/SONAR-6151) to work on it.

We are also thinking of excluding `System.*` as the default value so others will have less issue with this.
