### ISSUE TITLE
Convert SonarAnalyzer.* projects to VS2017 and target .NET Standard

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#569]
- [x] convert analyzer projects
- [x] convert unit test projects
- [x] make all failing tests pass (thanks Ammo)
    - [x] it seems that references to System.Collections.Immutable are not added (see MutableFieldsShouldNotBePublicStaticTest.cs)
    - [x] should better handle reflection types - many methods are missing, e.g. should use GetTypeInfo instead
- [x] convert doc generator
- [x] convert vsix project
- [x] create nuget packages
- [x] decide on strategy for VS2015 compatibility
    - [x] use the following roslyn nugets - for 2017 projects - 2.0.x (e.g. support VS2017 no updates) and for 2015 projects - 1.3.x (VS2015 update 3), where x is latest available patch number. 
- [x] try to reduce the .net standard reference - currently it is 1.4, but we could go down IMO. This should not be a big problem for the majority of the developers, but could affect those who work on WP applications (very few); see first what .netstandard is referenced by the Roslyn packages.
- [x] fix debugging vsix (Google.Protobuf.dll not included)
- [ ] update the ruling execution: 
    - [ ] VS2015 - cannot find System.Collections.Immutable 1.21... - seems that the references to the common stuff should be changed. Be careful not to update the references to Microsoft.CodeAnalysis.*!
    - [x] VS2017
- [ ] fix import of signing.cs
- [ ] update build scripts to build the new solutions and generate two sets of packages (for 2015 and 2017)
    - [ ] Scanner for MSbuild should be able to scan VS2017 solutions (as ours is now such)
- [ ] update the build machines so that the analyzers are built with VS2017

**Comment by Evangelink** [comment]
@valhristov this might help to take a decision on supported versions: https://github.com/dotnet/roslyn/wiki/NuGet-packages

Version 1.3.2 is the latest update compatible with VS 2015 U3 (so we already drop VS2015 U0, U1 and U2).
