### ISSUE TITLE
Rule S3693: Exception constructors should not throw exceptions

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-csharp#584]
[RSPEC-3693](https://jira.sonarsource.com/browse/RSPEC-3693)

It may be a good idea to raise an exception in a constructor if you're unable to fully flesh the object in question, but not in an exception constructor. If you do, you'll interfere with the exception that was originally being thrown. Further, it is highly unlikely that an exception raised in the creation of an exception will be properly handled in the calling code, and the unexpected, unhandled exception will lead to program termination.

**Comment by jinek** [comment]
Where does this rule come from? What is the idea behind it? 

Asking, because "Not to throw exception" from "somewhere" in c# is not possible. Runtime and .NET itself can throw exception from anyplace where it is necessary
