### ISSUE TITLE
Google.Protobuf.dll is not included in the dev vsix

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#586]
The VSIX project for VS2015 and 2017 do not include Google.Protobuf.dll, this results in exceptions in the metrics analyzers. Everything else seems to be working.

**Comment by valhristov** [comment]
No idea what's preventing the dll from being included. The manifest files are virtually the same.

**Comment by Evangelink** [comment]
Solved as part of the .Net Core migration (linked to the migration).
