### ISSUE TITLE
Fix S3925: Call to 'base.GetObjectData' is not properly detected

### ISSUE THREAD

**Issue by jcurl** [SonarSource/sonar-csharp#589]
### Description

The warning S3925 triggers for much of my exception code. 

### Repro steps

The following code is simplified from the .NET reference sources for [ArgumentException](https://referencesource.microsoft.com/#mscorlib/system/argumentexception.cs,109b3ef6299ef9df):

```
    [Serializable]
    public class MyArgumentException : SystemException, ISerializable
    {
        private string m_paramName;

        public MyArgumentException() : base(string.Empty) { }

        public MyArgumentException(String message) : base(message) { }

        public MyArgumentException(String message, Exception innerException)
            : base(message, innerException) { }

        public MyArgumentException(String message, String paramName, Exception innerException)
            : base(message, innerException)
        {
            m_paramName = paramName;
        }

        public MyArgumentException(String message, String paramName) : base(message)
        {
            m_paramName = paramName;
        }

        protected MyArgumentException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
            m_paramName = info.GetString("ParamName");
        }

        public override String Message
        {
            get
            {
                if (!String.IsNullOrEmpty(m_paramName)) {
                    return m_paramName;
                } else
                    return base.Message;
            }
        }

        public virtual String ParamName
        {
            get { return m_paramName; }
        }

        public override void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            if (info == null) throw new ArgumentNullException("info");
            base.GetObjectData(info, context);
            info.AddValue("ParamName", m_paramName, typeof(String));
        }
    }
```

If I change SystemException to Exception then it doesn't complain.

But then I have problems with this code (OptionException has no error, but then a derived class that has its own data does, and as far as I can tell, it's correct):

```
    [Serializable]
    public class OptionException : Exception
    {
        public OptionException() { }
        public OptionException(string message) : base(message) { }
        public OptionException(string message, Exception innerException) : base(message, innerException) { }
        protected OptionException(SerializationInfo info, StreamingContext context) : base(info, context) { }
    }

    [Serializable]
    public class OptionUnknownException : OptionException
    {
        private string m_Option;

        public OptionUnknownException() { }

        public OptionUnknownException(string option)
            : base("Unknown option '" + option + "'")
        {
            m_Option = option;
        }
        public OptionUnknownException(string option, Exception innerException)
            : base("Unknown option '" + option + "'", innerException)
        {
            m_Option = option;
        }

        public OptionUnknownException(string option, string message) : base(message)
        {
            m_Option = option;
        }

        protected OptionUnknownException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
            m_Option = info.GetString("option");
        }

        public override void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue("option", m_Option);
            base.GetObjectData(info, context);
        }

        public virtual String Option
        {
            get { return m_Option; }
        }
    }
```

If I change `public class OptionUnknownException : OptionException` to `public class OptionUnknownException : Exception` then there is no warning, but this is not the code I want.

### Expected behavior

It should not complain about S3925. As far as I can tell, it conforms to the serialization pattern.
* The System.SerializableAttribute attribute is missing. **The attribute is present.**
* Non-serializable fields are not marked with the System.NonSerializedAttribute attribute. **I don't have non-serializable fields**
* There is no serialization constructor. **There is a serialization constructor**
* An unsealed type has a serialization constructor that is not protected. **It's unsealed and it is protected**
* A sealed type has a serialization constructor that is not private. **N/A**
* An unsealed type has a ISerializable.GetObjectData that is not both public and virtual. **It's public and virtual (overridden)**
* A derived type has a serialization constructor that does not call the base constructor. **It calls the base constructor**
* A derived type has a ISerializable.GetObjectData method that does not call the base method. **It calls the base method**
* A derived type has serializable fields but the ISerializable.GetObjectData method is not overridden. **The private string is serializable and is called**

It also appears to conform to [MSDN Sample Code](https://blogs.msdn.microsoft.com/agileer/2013/05/17/the-correct-way-to-code-a-custom-exception-class/) for writing an exception:

### Actual behavior

The class `MyArgumentException` raises S3925.

### Known workarounds

None known.

### Related information

* SonarC# Version 3.3.0
* Visual Studio Version 2015

**Comment by michalb-sonar** [comment]
Thanks for reporting this (and few other) issues @jcurl. Feedback is always appreciated, especially with good repro cases!

This is a false positive; your code is correct indeed. The analyzer complains about missing `base.GetObjectData` call in your `GetObjectData` - but it clearly is there.

**Comment by pavel-mikula-sonarsource** [comment]
@DreadLordMikey Our example has non-public constructor with `SerializationInfo`, yours is public.

The secondary location message says "Make this constructor protected" on the constructor with `SerializationInfo` parameters. This is unfortunately not visible in SonarLint, only SonarCloud and SonarQube.

Please refer to community.sonarsource.com for any follow up discussion. This thread was closed 5 years ago and you should not expect any responses on it.
