### ISSUE TITLE
Fix S3242: Rule should not trigger on interface methods

### ISSUE THREAD

**Issue by SamuelEnglard** [SonarSource/sonar-csharp#596]
While the usage in the method may allow for a more base type, since the interface requires the higher type triggering S3242 is invalid.

**Comment by Evangelink** [comment]
Hi @SamuelEnglard ! 
Do you mean that we recommend to use a less derived type on a method parameter while this method is actually the implementation of an interface?

**Comment by SamuelEnglard** [comment]
@Evangelink yes
