### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by wekempf** [SonarSource/sonar-csharp#597]
### Description

In my code base I'm getting the following error from Sonar C#.

```
'SonarAnalyzer.Rules.CSharp.ObjectsShouldNotBeDisposedMoreThanOnce' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.MemberBindingExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax'.'.
```

### Repro steps

Don't know how to give you a repro, but the exception message should really be enough to fix this.

### Expected behavior

No exception should be thrown.

### Actual behavior

Exception is thrown due to invalid cast.

### Known workarounds

None.

### Related information

* SonarC# Version: v1.4.0
* Visual Studio Version: VS 2017

**Comment by Evangelink** [comment]
Hi @wekempf,

Thanks for reporting this bug.
I am pretty sure that I covered this case while handling #587.
