### ISSUE TITLE
Update S3962: Ignore public static readonly fields

### ISSUE THREAD

**Issue by williamdiesny** [SonarSource/sonar-csharp#607]
### Description

The solution proposed by the rules S3962 and S2339 are not compatible.

**Rule S3962** : Change static readonly into const,
**Rule S2339** : Change public constant into static readonly.

I think the rule S3962 should be applied only on **non public** constant.

**Comment by michalb-sonar** [comment]
Thanks for reporting @williamdiesny. That's a good suggestion.

**Comment by williamdiesny** [comment]
I made a pull-request, hope this help...

#609

**Comment by MaxTranced** [comment]
IMHO S3962 should also ignore internal visibility fields if the containing assembly is using
`[assembly: InternalsVisibleTo("AnotherAssembly")]`
This is probably an infrequent case, just thought I'd mention it here to get thoughts.

**Comment by valhristov** [comment]
@MaxTranced we thought about that when we developed the fix, but it is rather difficult to check for assembly attributes from an analyzer that works on class level. It could be done, but in exchange for significant complexity increase...

**Comment by MaxTranced** [comment]
@valhristov that makes sense. Thank you!
