### ISSUE TITLE
Rule S2639: Inappropriate regular expressions should not be used

### ISSUE THREAD

**Issue by michalb-sonar** [SonarSource/sonar-csharp#618]
[RSPEC-2639](https://jira.sonarsource.com/browse/RSPEC-2639)

Regular expressions are powerful but tricky, and even those long used to using them can make mistakes.

**Comment by Evangelink** [comment]
Rule is handling replacement on string was internally use regex. This is not the case for C# so this rule doesn't make sense for us.
