### ISSUE TITLE
version of the sonar-csharp plugin compatible for SonarQube Server 5.1.2 

### ISSUE THREAD

**Issue by elopalv** [SonarSource/sonar-csharp#620]
### Description

I have SonarQube Server 5.1.2 installed. I need to install the sonar-csharp plugin compatible for my the server. Which version of the sonar-csharp plugin should I install?

Best regards.

**Comment by Evangelink** [comment]
Hi @elopalv,

Sadly we no longer support this version of SonarQube (the LTS is 5.6) so we have no matrix to know up to which version on SonarC# you can use.
