### ISSUE TITLE
S3928 should respect nameof()

### ISSUE THREAD

**Issue by WebDucer** [SonarSource/sonar-csharp#653]
### Description

Currently this rule check for the name of the parameter, if it is a plain string. If we use `nameof(parameterName)` this rule fails.

### Repro steps

To reproduce

1. Create a method with parameters.
2. Check this parameters agains `NULL` and throw `ArgumentNullException` with parameter  name as plain string.
3. The rule S3928 pass
4. Chachge from plain string to `nameof(parameterName)` the rue S3928 fails.

### Expected behavior

Rule S3928 respect and check both writings (plain string and nameof).

### Actual behavior

Rule S3928 respect only plain string.

### Known workarounds

Turn rule off.

### Related information

* SonarC# Version: 6.2 (build 2536)
* Visual Studio Version: VS 2017.2
* If running through the Scanner for MSBuild, its version: 3.0.3.778

**Comment by Evangelink** [comment]
Hi @WebDucer,

I have tried with the following piece of code:
```
void Foo(object o)
{
    if (o == null)
    {
        throw new ArgumentNullException(nameof(o)); // Compliant
        throw new ArgumentNullException(nameof(o), "Argument is null"); // Compliant
        throw new ArgumentNullException("Argument is null", nameof(o)); // Noncompliant
    }
}
```
And I couldn't reproduce the issue. The only case triggering is the 3rd one where I have inverted the `parameterName` and the `message`.

Could you tell me if you have the error with this piece of code? If so could you make a quick test with 6.3?

**Comment by WebDucer** [comment]
Hello @Evangelink 

I tried the same code with version 6.3 and it works. Now I activated the rule again for my projects.

Thanks

**Comment by DeChrist** [comment]
Hello @Evangelink 

according to the MSDN Documentation [ArgumentException Constructor (String, String)](https://msdn.microsoft.com/en-us/library/sxykka64(v=vs.110).aspx) the _paramName_ is the **second ** argument, not the first.

The rule as implemented is therefore not correct (in fact it invalidates correct code).

Furthermore, there should be _no check_ when there is only one string argument, as it is then the exception _message_.

**Comment by Evangelink** [comment]
Hi @DeChrist,

Do you have the issue in your code or are you simply commenting based on this PR? I am asking because my [test cases] (https://github.com/SonarSource/sonar-csharp/blob/master/sonaranalyzer-dotnet/src/Tests/SonarAnalyzer.UnitTest/TestCases/CheckArgumentException.cs#L54) seem to handle properly the switch of position.

If you are having any issue, could you create a new issue in the backlog so we can track it easily?

Cheers,
Amaury

**Comment by peteraritchie** [comment]
This false positive happens with local functions:
![image](https://user-images.githubusercontent.com/408620/70557465-da2df500-1b50-11ea-8a8e-69d4666287a4.png)

**Comment by andrei-epure-sonarsource** [comment]
@peteraritchie could you please open a new issue for this local functions FP?

**Comment by StingyJack** [comment]
@andrei-epure-sonarsource  This also doesnt like when we use properties of an argument. 

```
       public UserManagementServices(ILogger logger, UserManagementServiceConfig userManagementServiceConfig)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            if (userManagementServiceConfig == null)
            {
                throw new ArgumentNullException(nameof(userManagementServiceConfig));
            }

            if (string.IsNullOrWhiteSpace(userManagementServiceConfig.DataServiceBaseUrl))
            {
                throw new ArgumentNullException(nameof(userManagementServiceConfig.DataServiceBaseUrl)); //<-- this reports S3928  violation, even though its the argument property we are checking.
            }
```

This is kind of a pain because the function argument is a composite input object created to avoid the "too many parameters" violation.  Does that need a new ticket too?

**Comment by pavel-mikula-sonarsource** [comment]
Hi @StingyJack, `DataServiceBaseUrl` is not an argument of your method so `ArgumentNullException` is not appropriate exception to throw. So S3928 is working well and warning you about bad pattern. You should use `InvalidOperationException` for this case.

**Comment by StingyJack** [comment]
It's a property of an argument. An argument that is a parameter bag that was created to resolve the "too many parameters" issue.

I've refactored the whole bag out in the meantime, but will try to remember to test out using nameof for both the param and it's property

**Comment by StingyJack** [comment]
@pavel-mikula-sonarsource - part of the argument is null, and an ArgNullEx is semantically more correct and appropriate for someone to start troubleshooting a problem from ("Something wrong with the function argument") than the more general InvalidOpEx ("program cannot continue at this point")

This rule also triggers a false positive in this scenario as well. I had not yet installed the nuget package with the `IMyLogger` in it and the S3928 pops up, apparently not knowing the parameter list. (do these not analyze the source code?)

![image](https://user-images.githubusercontent.com/15381181/111892481-4218ef80-89d2-11eb-83d7-ef16e6c2a30a.png)

**Comment by pavel-mikula-sonarsource** [comment]
While it intuitively seems relevant as it's related to a null check, it's against the official documentation. You can also introduce your own `ArgumentPropertyNullException` for example to describe the nameof(argument name) as well as nameof(that null property) if you'd like to have a better design for the wrapped case.

For the second problem with empty name: please create a new issue. This looks like a glitch in the implementation where `analysisContext.SemanticModel.GetConstantValue(argumentExpression)` uses semantic model and cannot resolve the value of nameof argument (presumably due to a missing type information).

**Comment by StingyJack** [comment]
@pavel-mikula-sonarsource  if not an ArgNullEx then an ArgEx is more appropriate than an InvalidOpEx. Created #4180 for the second part.
