### ISSUE TITLE
<query>sonarqube with dotnet msbuild on Linux 

### ISSUE THREAD

**Issue by arpit-nagar** [SonarSource/sonar-csharp#670]
Good to see PR #669  sonar-charp is migrating to dot net core.
Do we have any ETA for sonarqube with dotnet msbuild on Linux ?

**Comment by FastNinja** [comment]
how we can run that on Linux machines? trying to analyze dotnet core  code using linux stack (so Windows machine is out of questions)...

**Comment by fmallet** [comment]
Hi here, this is indeed in our roadmap to support dotnet core and to make it possible to analyze .Net projects on any OS but we can't commit on any ETA for the timebeing. Thanks for your understanding.
