### ISSUE TITLE
Update SonarLint website to mention GitHub repository as a place to file issues

### ISSUE THREAD

**Issue by ohadschn** [SonarSource/sonar-csharp#684]
The [SonarLint for Visual Studio site](http://www.sonarlint.org/visualstudio/index.html) only mentions this repository as a place to contribute, suggesting StackverFlow and the Google group for everything else. However it seems opening issues here is the best way to go. For example, the message I opened in the Google group about `SuppressMessage` was ignored, and here it was not only addressed but actually fixed and released...

**Comment by Evangelink** [comment]
Hi @ohadschn.

You are right we have been less active on the `Google Group` and `StackOverflow` compared to the `GitHub` issues. I think your suggestion is a good one.

**Comment by Evangelink** [comment]
@valhristov @michalb-sonar Let's update the website on the next release.
