### ISSUE TITLE
Fix S3242: Should not suggest base class for arguments when method has an event handler signature

### ISSUE THREAD

**Issue by Portikus** [SonarSource/sonar-csharp#705]
### Description

Hi there,

If you create a blank new UWP App you will get a S3242 false positive. The analyser suggests to use a `INavigationFailedEventArgs` instead of `NavigationFailedEventArgs` in the event handler for the `Frame.OnNavigationFailed` event handler. But `INavigationFailedEventArgs` is inaccsessible due to its protection level.

### Repro steps
I created a small [repo solution]((https://github.com/SonarSource/sonar-csharp/files/1233687/S3242FalsePositive.zip) with an UWP app. In the App.xaml.cs you can see the warning in row 71. If you change the parameter type of `args` to `INavigationFailedEventArgs` you will get a compiler error CS0122

### Expected behavior

No S3242 warning on an UWP event handler if the genreal type of a parameter is inaccsessible due to its protection level.

### Actual behavior

A S3242 warning on an UWP event handler if the genreal type of a parameter is inaccsessible due to its protection level.

### Known workarounds

No workaround known.

### Related information

* SonarC# Version: 6.3.0.2862
* Visual Studio Version: 15.3.0

**Comment by valhristov** [comment]
Thanks for the feedback, we will be working on this in the near future.

**Comment by Evangelink** [comment]
Sorry I thought there was another problem I didn't fixed but it is all good.
