### ISSUE TITLE
Exceptions after enabeling connection to Sonarqube server in Visual Studio 

### ISSUE THREAD

**Issue by ValentijnMakkenze** [SonarSource/sonar-csharp#709]
### Description

I created a connection to our sonarqube server in VS2015 and did a complete rebuild

### Repro steps

Not sure how to reproduce, its a big solution (116 projects, 652K loc) 

### Expected behavior

Please provide a description of the behavior you expect.

No warnings about problems in analyzers

Please provide a description of the actual behavior you observe.

I did not expect these distinct warnings  (actual number of warning was 158 but these are the unique ones):
Warning | CS8032 | An instance of analyzer   SonarAnalyzer.Rules.CSharp.ThrowReservedExceptions cannot be created from   C:\Git\NSR   master\GVR\packages\SonarAnalyzer.CSharp.6.3.0.2862\analyzers\SonarAnalyzer.CSharp.dll:   Method 'GetLocation' in type 'SonarAnalyzer.Rules.CSharp.ThrowReservedExceptions'   from assembly 'SonarAnalyzer.CSharp, Version=6.3.0.0, Culture=neutral,   PublicKeyToken=c5b62af9de6d7244' does not have an implementation..
Warning | AD0001 | Analyzer   'SonarAnalyzer.Rules.CSharp.ObjectsShouldNotBeDisposedMoreThanOnce' threw an   exception of type 'System.TypeLoadException' with message 'Could not load   type 'SonarAnalyzer.Helpers.FlowAnalysis.Common.BaseExplodedGraph' from   assembly 'SonarAnalyzer, Version=6.2.0.0, Culture=neutral,   PublicKeyToken=c5b62af9de6d7244'.'.
Warning | AD0001 | Analyzer   'SonarAnalyzer.Rules.CSharp.PublicMethodArgumentsShouldBeCheckedForNull'   threw an exception of type 'System.TypeLoadException' with message 'Could not   load type 'SonarAnalyzer.Helpers.FlowAnalysis.Common.BaseExplodedGraph' from   assembly 'SonarAnalyzer, Version=6.2.0.0, Culture=neutral,   PublicKeyToken=c5b62af9de6d7244'.'.
Warning | AD0001 | Analyzer 'SonarAnalyzer.Rules.CSharp.InvalidCastToInterface' threw an   exception of type 'System.TypeLoadException' with message 'Could not load   type 'SonarAnalyzer.Helpers.FlowAnalysis.Common.BaseExplodedGraph' from   assembly 'SonarAnalyzer, Version=6.2.0.0, Culture=neutral,   PublicKeyToken=c5b62af9de6d7244'.'.
Warning | AD0001 | Analyzer 'SonarAnalyzer.Rules.CSharp.NullPointerDereference' threw an   exception of type 'System.TypeLoadException' with message 'Could not load   type 'SonarAnalyzer.Helpers.FlowAnalysis.Common.BaseExplodedGraph' from   assembly 'SonarAnalyzer, Version=6.2.0.0, Culture=neutral,   PublicKeyToken=c5b62af9de6d7244'.'.
Warning | AD0001 | Analyzer 'SonarAnalyzer.Rules.CSharp.ConditionEvaluatesToConstant' threw   an exception of type 'System.TypeLoadException' with message 'Could not load   type 'SonarAnalyzer.Helpers.FlowAnalysis.Common.BaseExplodedGraph' from   assembly 'SonarAnalyzer, Version=6.2.0.0, Culture=neutral,   PublicKeyToken=c5b62af9de6d7244'.'.
Warning | AD0001 | Analyzer 'SonarAnalyzer.Rules.CSharp.EmptyNullableValueAccess' threw an   exception of type 'System.TypeLoadException' with message 'Could not load   type 'SonarAnalyzer.Helpers.FlowAnalysis.Common.BaseExplodedGraph' from   assembly 'SonarAnalyzer, Version=6.2.0.0, Culture=neutral,   PublicKeyToken=c5b62af9de6d7244'.'.

### Related information

* SonarC# Version
6.3.0.2862
* Visual Studio Version
Version 14.0.25431.01 Update 3
* If running through the Scanner for MSBuild, its version
--

**Comment by Evangelink** [comment]
Hi @ValentijnMakkenze ,
I can see multiple versions of the analyzer in your stacktrace. Are you using SonarLint for VS while having some projects with a manual reference to the nuget SonarAnalyzer.CSharp?
Are you a new user of the connected mode or have you simply done an upgrade? In the second case, could you tell us which version of SonarLint/SonarC# you have migrated from and to?

**Comment by ValentijnMakkenze** [comment]
Hi @Evangelink 

You are spot on, this was the first time I used connected mode but I also added the NuGet package to the test projects manually and I think that's where I got the newer version of NuGet and older version of SonarLint. I updated everything to the latest version and the warnings are gone. 

Except the 4287 ones from the analyzer :)

**Comment by ValentijnMakkenze** [comment]
I'm closing this issue
