### ISSUE TITLE
Update S3415: Support other test frameworks

### ISSUE THREAD

**Issue by michalb-sonar** [SonarSource/sonar-csharp#722]
Currently the rule only checks for MS-Test, it should also cover NUnit and Xunit.

[RSPEC-3415](https://jira.sonarsource.com/browse/RSPEC-3415) needs to be updated accordingly.

**Comment by Evangelink** [comment]
Hi @michalb-sonar I am pretty sure you are mentioning the wrong rule here since S3414 is not yet implemented and is not directly related to test frameworks. Please update title and description.

**Comment by michalb-sonar** [comment]
@Evangelink good catch! I've corrected the number, it should be S3415

**Comment by valhristov** [comment]
I think we are supporting NUnit and XUnit as well, see the PR #678

**Comment by Evangelink** [comment]
@valhristov no we only support VSTest see the PR :)

**Comment by valhristov** [comment]
Ok, I admit the rule does not support other frameworks than MSTest, I got fooled by the many unrelated changes in the PR :)
