### ISSUE TITLE
The 'SonarLintDaemonPackage' package did not load correctly.

### ISSUE THREAD

**Issue by dougheeren** [SonarSource/sonar-csharp#723]
![2017-08-25 07_44_02-](https://user-images.githubusercontent.com/802273/29714975-f47936ce-896a-11e7-80d9-89c31f0f8664.png)
![2017-08-25 07_50_52-about microsoft visual studio](https://user-images.githubusercontent.com/802273/29714974-f4767c36-896a-11e7-8d14-9131d68d3958.png)

![2017-08-25 07_44_02-](https://user-images.githubusercontent.com/802273/29714985-fb73b2ce-896a-11e7-8934-af5b094f825a.png)

### Description

When loading visual studio a user is prompted with a dialogue box that indicates SonarLint did not load correctly. SonarLint does not function afterward. This appeared to happen after a recent Visual Studio Upgrade and a reinstall does not correct the issue. 

### Repro steps

Install the above version of Visual Studio. Patch it to the latest and load a project. It is happening to multiple programmers in our office. We also use OzCode and while I don't think the two packages are incompatible it may be something to look at. 

### Expected behavior

The dialogue box should not show and the user should see SonarLint suggestions in C# code afterward.

### Actual behavior

You receive a dialogue box and the attached log files after loading Visual Studio and SonarLint does not appear to be offering code suggestions afterward. 

### Known workarounds

I haven't found any.

### Related information

Microsoft Visual Studio Enterprise 2017  (Enterprise)
Version 15.3.2
VisualStudio.15.Release/15.3.2+26730.10
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00369-60000-00001-AA949
Microsoft Architecture Diagrams and Analysis Tools

Visual Basic 2017   00369-60000-00001-AA949
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA949
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA949
Microsoft Visual C++ 2017

Add New File   3.5
The fastest and easiest way to add new files to any project - including files that start with a dot

ASP.NET and Web Tools 2017   15.0.30726.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Template Engine 2017   15.0.30726.0
ASP.NET Template Engine 2017

ASP.NET Web Frameworks and Tools 2012   4.0.20601.0
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2017   5.2.50601.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30728.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.9000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Data Lake Tools for Visual Studio   2.2.9000.1
Microsoft Azure Data Lake Tools for Visual Studio

Bundler & Minifier   2.4.340
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

CSS Tools   1.0.14
Provides additional features to the CSS editor in Visual Studio.

Editor Enhancements   1.0.27
Provides additional features such as HTML and URL encodings, transformations and sorting of selected text the editor.

EditorConfig Language Service   1.17.207
Language service for .editorconfig files.

EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer

File Nesting   2.6.67
Automatically nest files based on file name and enables developers to nest and unnest any file manually

GitHub.VisualStudio   2.2.0.11
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

HTML Tools   1.0.3
Productivity tools for the HTML editor

Image Optimizer   3.6.103
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

Image Sprites   1.4.47
Boost your website's performance by creating image sprites to reduce the amount of HTTP requests needed.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Transpiler   0.9.24
The simplest way to transpile JS and JSX to EcmaScript 5 without any complicated node.js tools in your project. It uses the TypeScript compiler behind the scenes.

Markdown Editor   1.11.214
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft Azure HDInsight Azure Node   2.2.9000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.2.9000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   1.7
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.2.9000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50719.1

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.1.179
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

OzCode   1.0
Your road to Magical Debugging. http://www.oz-code.com

OzCodePackage Extension   1.0
OzCodePackage Visual Studio Extension Detailed Info

Package Installer   2.0.101
Makes it easier, faster and more convenient than ever to install Bower, npm, Yarn, JSPM, TSD, Typings and NuGet packages to any project

Package Security Alerts   1.0.17
Identifies npm and Bower packages that contains known security vulnerabilities to ensure your project is always using the most secure package versions.

Project File Tools   1.0.1
Provides Intellisense and other tooling for XML based project files such as .csproj and .vbproj files.

SlowCheetah - XML config transforms   1.0
This package enables you to transform your app.config or any other XML file based on the build configuration. It also adds additional tooling to help you create XML transforms.

SonarLint for Visual Studio   3.4.0.1732
SonarLint is an extension to your favorite IDE that provides on-the-fly feedback to developers on new bugs and quality issues injected into their code.

SQL Server Data Tools   15.1.61707.200
Microsoft SQL Server Data Tools

Syntax Highlighting Pack   2.7.125
Adds syntax highlighting and snippet support for a wide variety of programming languages such as Clojure, Go, Jade, Lua, Swift, Ruby and many more...

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.3.4.0
TypeScript tools for Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake

Vue.js Pack 2017   1.1.8
Contains HTML Intellisense and code snippets for the Vue.js JavaScript library

Web Compiler   1.11.326
Compiler for LESS, Sass and CoffeeScript files

WebJobs Tools v1.0.0   15.0.30812.0
WebJobs Tools v1.0.0

ZenCoding   1.2.11
Provides ZenCoding for the HTML Editor - full support for static HTML, Razor and WebForms.
[LoadingBugFiles.zip](https://github.com/SonarSource/sonar-csharp/files/1251889/LoadingBugFiles.zip)

**Comment by Evangelink** [comment]
Hi @dougheeren,

We are aware of this bug (see here [sonarlint-visualstudio](https://github.com/SonarSource/sonarlint-visualstudio/issues/243)) and it should be fixed with the next release. We are starting the RFF period now so please if you have some time to test the new extension we are looking for feedback as we didn't manage to reproduce the problem internally.

**Comment by dougheeren** [comment]
I do have some time to test it and can get multiple setups going since most of the developers in our office are having the issue.

**Comment by Evangelink** [comment]
We are into the release process so stay tuned for the email on the Google Group or the [GitHub release page](https://github.com/SonarSource/sonarlint-visualstudio/releases)

**Comment by dougheeren** [comment]
Will do. Thank you for the prompt response. We are moving to Bitbucket and most likely sonarqube so getting this working prior to that is critical. Thanks again.
