### ISSUE TITLE
Update from 6.3 to 6.4 lost references in .csproj file

### ISSUE THREAD

**Issue by RalfKoban** [SonarSource/sonar-csharp#738]
### Description

I just upgraded from 6.3 to 6.4. The references in the C# project file (.csproj) for 6.3 had been successfully removed but the references for 6.4 had not been added.

### Repro steps

Please provide the steps required to reproduce the problem

1. Install 6.3.
2. Update to 6.4.

### Expected behavior

After update, the references no longer point to 6.3 but to 6.4.

### Actual behavior

References were lost. However, the packages.config was updated properly.
(Please note that I manually added a condition for the item group, see code below.)

### Known workarounds

Uninstall 6.3 Then install 6.4.

### Related information

* SonarC# Version (6.3/6.4)
* Visual Studio Version 2017 (v15.3.3)

* Relevant project file content:
```
  <ItemGroup Condition="'$(NCrunch)' != '1'">
    <Analyzer Include="..\Solution\packages\SonarAnalyzer.CSharp.6.3.0.2862\analyzers\Google.Protobuf.dll" />
    <Analyzer Include="..\Solution\packages\SonarAnalyzer.CSharp.6.3.0.2862\analyzers\SonarAnalyzer.CSharp.dll" />
    <Analyzer Include="..\Solution\packages\SonarAnalyzer.CSharp.6.3.0.2862\analyzers\SonarAnalyzer.dll" />
  </ItemGroup>
```

**Comment by Evangelink** [comment]
Hi @RalfKoban,
Thanks for the feedback we will have a look at it soon.

**Comment by duncanp-sonar** [comment]
Repro-ed for VS2017.4.1 with a .Net Framework console app. The more recent versions of the NuGet package fail to updated correctly the same way.

Required changes: the project system in VS2017 knows how to handle installing analyzers so our install.ps1/uninstall.ps1 scripts need to be updated.
The default install/uninstall scripts for new analyzer projects in 2017 start with the following:

```
if($project.Object.SupportsPackageDependencyResolution)
{
    if($project.Object.SupportsPackageDependencyResolution())
    {
        # Do not install analyzers via install.ps1, instead let the project system handle it.
        return
    }
}
```  

The VS2015 NuGet packages still update as expected.
