### ISSUE TITLE
Rule S1110: Redundant parenthesis - move the implementation from S3235

### ISSUE THREAD

**Issue by michalb-sonar** [SonarSource/sonar-csharp#752]
[RSPEC 3235](https://jira.sonarsource.com/browse/RSPEC-3235) is marked as a duplicate of [RSPEC 1110](https://jira.sonarsource.com/browse/RSPEC-1110). All other languages apart from C# have implemented this rule under S1110, so we should be consistent.

**Comment by Evangelink** [comment]
@michalb-sonar Not sure we can change a rule ID for an active rule. I will let you double check with Freddy and Jesse

**Comment by valhristov** [comment]
We frequently talk about this rule :) We decided to keep it like this for backwards compatibility with existing issues. But perhaps we should bite the bullet and fix it. WDYT?

**Comment by Evangelink** [comment]
I have no problem about fixing this as long as it is ok from the company point of view to delete a rule that is used in production. That's why I was suggesting @michalb-sonar to discuss with Jesse and Freddy.

**Comment by michalb-sonar** [comment]
I've checked with @jccollet before raising this ticket. @fmallet, do you have an opinion on the rule id change?

**Comment by Evangelink** [comment]
Just had a talk with @ganncamp and she suggests to deprecate S3235 and to implement S1110 (duplicating code).

**Comment by valhristov** [comment]
S3235 was originally just for removing parenthesis of class constructors when an object initializer is used:

var x = new A() { B = b }; // noncompliant

var x = new A { B = b };

Not really sure if this should be moved to S1110...

**Comment by Evangelink** [comment]
Oh... Haven't paid attention.... I have just seen the ticket in the backlog and was not convinced by the way to handle it (described by @michalb-sonar).
