### ISSUE TITLE
Using Visual Studio Test task (version 2.*) in VSTS doesn't produce coverage in analysis results

### ISSUE THREAD

**Issue by mvandevy** [SonarSource/sonar-csharp#776]
### Description

We have our build configured in VSTS where we are using SonarQube Scanner for MSBuild version 3.0.2
Preceding the 'Complete the SonarQube Analysis' task there is a Visual Studio Test task in which the 'Code Coverage Enabled' is marked. So the test task produces a .coverage file. When using the 1.* version of the Visual Studio Test task the .coverage file is picked up and probably converted to a .coveragexml file providing us with coverage statistics in the analysis of the project. When using the 2.* version of the Visual Studio Test task the .coverage file is also produced, but there are no coverage statistics available in the analysis of the project.

### Repro steps

Success: Configure 'Code Coverage Enabled' in version 1.* of the Visual Studio Test task.
Fail: Configure 'Code Coverage Enabled' in version 2.* of the Visual Studio Test task.

### Expected behavior

Coverage is picked up by hthe 'Complete the SonarQube Analysis' task whether version 1.* or 2.* is used of the Visual Studio Test task.

### Actual behavior

The coverage is not picked up and used with the 2.* version of the Visual Studio Test task.

### Known workarounds

Don't use the 2.* version of the Visual Studio Test task.

### Related information

* SonarQube Scanner for MSBuild version 3.0.2

**Comment by salixzs** [comment]
Try this workaround
https://github.com/SonarSource/sonar-csharp/issues/492#issuecomment-320704456

**Comment by mvandevy** [comment]
Thanks for the update. I already tried the workaround, but it didn't seem to work. Probably did something wrong previously as I've tried it again and it seems to work now. Thank you.
