### ISSUE TITLE
Fix S3242: Do not suggest ICollection<KVP<TKey, TValue>>

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-csharp#782]
The current implementation of the rule is currently raising quite a lot of FP and we should came up with some ideas about tuning the rule to Kill the Noise.

For example:
1/ Do not suggest a non-generic base type (i.e. not `IEnumerable` over `IEnumerable<T>`).

2/ Do not suggest `ICollection<KeyValuePair<TKey, TValue>>` over `IDictionary<TKey, TValue>`.

Let's have a look at sonarcloud and peach to try to find the right patterns.

**Comment by Evangelink** [comment]
I cannot reproduce the issue (neither the non-generic nor the `ICollection<KeyValuePair<TKey, TValue>>`).

**Comment by michalb-sonar** [comment]
Re 2)
```
public void Test_03(Dictionary<string, string> foo)
{
    var x = foo.Count;
}
```
