### ISSUE TITLE
Improve test rules to handle the 'TestCaseSource' attribute

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-csharp#785]
Most of the test rules we have rely on detecting some test attributes. @sm-g was pointing out the `TestCaseSourceAttribute` from NUnit that we don't handle yet.

S2187: #979 
S1607: #981
S2699: #983

**Comment by Evangelink** [comment]
`TestCaseSource` seems to be always used in pair with `Test` according to NUnit doc so it is safe to close this issue.

**Comment by sm-g** [comment]
Could you point to that docs page? I never saw such thing. And in fact Test attribute not need for tests with TestCaseSource.

**Comment by Evangelink** [comment]
@sm-g I got confused by the NUnit documentation for v2.5 (http://nunit.org/docs/2.5/testCaseSource.html) which is different from v3+. I am going to make some tests to see what's the real behavior.

**Comment by Evangelink** [comment]
This ticket was split into multiple smaller ones.
