### ISSUE TITLE
False positive on S1144

### ISSUE THREAD

**Issue by usmrtester** [SonarSource/sonar-csharp#788]
### Description

My application:  .net 4+, c#, Windows Application 

Getting false positive on various classes (S1144 messages).  I know this because there are many references to these classes and they are used every day in my application by 100+ users.

### Repro steps

Please provide the steps required to reproduce the problem

Compile code

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

Please provide a description of the behavior you expect.

no S1144 messages, this is a sonar bug.

Please provide a description of the actual behavior you observe.

no know workarounds, 

Please provide a description of any known workarounds.

no known workarounds

* SonarC# Version - 3.5.0.1803
* Visual Studio Version  MSVS 2017 Version 15.3.4
* If running through the Scanner for MSBuild, its version

**Comment by valhristov** [comment]
@usmrtester, yes, it is possible S1144 to show false positives in certain cases. Could you please send us a simple repro application or code snippets that can be used to observe the problem?

**Comment by usmrtester** [comment]
Following a good example.  Note that all the S1144's listed below have
references and are used (probably every 2 minutes) by 100+ users to update
part of an administrative application that shows user Sessions.  All of
these S1144's listed below are false positives.

[image: Inline image 1]

**Comment by usmrtester** [comment]
Here's an example project with the same S1144 messages.  zip file, just
rename.  Its a small project but demonstrates the issue exactly.
