### ISSUE TITLE
Line ending changes just after cloning and pulling master

### ISSUE THREAD

**Issue by wachulski** [SonarSource/sonar-csharp#812]
### Description

Cloning and pulling master leads to non-empty git index.

### Repro steps

1. Clone with pulling `master`
2. `git status`

### Expected behavior

3. No changed files

### Actual behavior

4. Changed files.

### Known workarounds

`Assume unchanged`

### Related information

Tried `core.autocrlf` set to `true`, `false`, ``. Each case ends up with changed files.

If you hard-reset to 295bae4e6a4a6f0f7b454c7273200022e69aed69 then no changes are reported. But if you hard-reset to 6c0d00cc05201a4ff8c942eaa9ad3087b2d9cf76 then file changes appear. This is due to the fact the latter is dated back to 24. Aug where the former (git attributes file) to 2. Oct. Most likely the problematic commit should have all line endings converted to `LF`, similarly to the effort done 31581c7559164dad9b177c00fe1e4b763fa4fea1. If so, there is a need to align new lines in all upcoming PRs containing commits earlier than the introduction of `.gitattributes` (yes, sounds cliche, but worthwhile).

**Comment by michalb-sonar** [comment]
Thanks for very good report @wachulski. We are aware of the issue and will address it shortly (ther were other priorities in the meantime).

**Comment by wachulski** [comment]
Thanks. Sure I understand. I went through that painful road a while ago for one of my projects. It's quite funny, it was about making https://github.com/gabrie-allaigre/sonar-gitlab-plugin to work with CRLF diffs stored in GIT internal db and served by Gitlab API. And it ended up with the fix to the sonar plugin (https://github.com/gabrie-allaigre/sonar-gitlab-plugin/pull/37).

**Comment by Evangelink** [comment]
@wachulski We are still not sure which direction we will go for so we have reverted the changes for now. I am closing the ticket as the new head is now working properly.

**Comment by wachulski** [comment]
Fair enough. Thanks.
