### ISSUE TITLE
Fix S3242: Do not suggest IReadOnlyCollection<T> interface instead of IReadOnlyList<T> if collection items are accessed by index

### ISSUE THREAD

**Issue by antrv** [SonarSource/sonar-csharp#813]
### Description

Wrong message about using IReadOnlyCollection<T> interface instead of IReadOnlyList<T> if collection items are accessed by index:
Consider using more general type 'System.Collections.Generic.IReadOnlyCollection<string>' instead of 'System.Collections.Generic.IReadOnlyList<string>'.

### Repro steps

```
public static long ParseNonNegativeLong(this IReadOnlyList<string> arguments, int index, string name)
{
    if (arguments == null || index < 0 || index >= arguments.Count)
        throw new JobArgumentException(index, name);

    if (!long.TryParse(arguments[index], out long result))
        throw new JobArgumentException(index, name, "Expected number.");

    return result;
}
```

### Expected behavior

No message.

### Actual behavior

There is the message from the analyzer:
Consider using more general type 'System.Collections.Generic.IReadOnlyCollection<string>' instead of 'System.Collections.Generic.IReadOnlyList<string>'.

### Related information

* SonarC# 6.4.1.3596
* Visual Studio 15.3.5

**Comment by Evangelink** [comment]
Hi @antrv ,
Thanks for the feedback! This is indeed a wrong suggestion and we will try to fix it soon.
