### ISSUE TITLE
Fix S3900: Arguments of public methods should be validated against null should take guarding methods into account

### ISSUE THREAD

**Issue by Corniel** [SonarSource/sonar-csharp#826]
A lot developers use Guarding to do their parameter checking.

The implementation that was once introduced by Microsoft itself (CA1062) supported this quite nicely by code that could look like the following:

``` C#
/// <summary>Supplies input parameter guarding.</summary>
public static class Guard
{
    /// <summary>Guards the parameter if not null, otherwise throws an argument (null) exception.</summary>
    /// <typeparam name="T">The type to guard; cannot be a structure.</typeparam>
    /// <param name="parameter">The parameter to guard.</param>
    /// <param name="paramName">The name of the parameter.</param>
    [DebuggerStepThrough]
    public static T NotNull<T>([ValidatedNotNull]T parameter, string paramName) where T : class
    {
        if (ReferenceEquals(parameter, null))
        {
            throw new ArgumentNullException(paramName);
        }
        return parameter;
    }
}

/// <summary>Marks the NotNull argument as being validated for not being null, to satisfy the static code analysis.</summary>
/// <remarks>
/// Notice that it does not matter what this attribute does, as long as
/// it is named ValidatedNotNullAttribute.
/// </remarks>
[AttributeUsage(AttributeTargets.Parameter)]
sealed class ValidatedNotNullAttribute : Attribute { }
```
So, if the parameter of the guarding method is decorated with an attribute with the name 'ValidatedNotNullAttribute' it is assumed to have done so.

Could this be added?

Also see https://esmithy.net/2011/03/15/suppressing-ca1062/

**Comment by Evangelink** [comment]
Hi @Corniel,
I think we should go for a broader solution but you are definitely right we should try to remove the False Positives raised by this rule.

**Comment by Corniel** [comment]
@Evangelink In which perspective should it be brother? As in, follow every path unil you find a null reference check? Might be okay too, but supporting the shortcut as Microsoft did it might still also be beneficial?!
