### ISSUE TITLE
Check for preferred use of language type aliases

### ISSUE THREAD

**Issue by mpetito** [SonarSource/sonar-csharp#866]
I'd like to encourage the use of the language type aliases to maintain consistency.

### Non-Compliant Code
`````
var foo = String.Empty;
Int32 bar;
`````

### Compliant Code
`````
var foo = string.Empty;
int bar;
`````

Is this an existing rule? I was unable to find it since these keywords are so common.

**Comment by Evangelink** [comment]
Hi @mpetito,

We don't currently have this feature/rule on our analyzer. I will discuss this with the team and get back to you.

**Comment by Evangelink** [comment]
Hi @mpetito,

We decided not to implement this rule. As said in the other post you can already find other tools `StyleCope Analyzer` or `.editorconfig` for this feature.
