### ISSUE TITLE
Display compiler warnings and errors

### ISSUE THREAD

**Issue by tijana88** [SonarSource/sonar-csharp#884]
In sonarqube c++ comunity plugin it is possible to have compiler warnings and errors presented in SonarQbe https://github.com/SonarOpenCommunity/sonar-cxx/issues/1066. This is very useful feature and great metric. 
Is there a plan to implement this feature also in c# plugin?

**Comment by Evangelink** [comment]
Hi @tijana88,

We had a similar question on the [SonarQube Google Group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/sonarqube/8RY_nR4GgEg/SDr7vWanAAAJ) in the beginning of the year. We replied that we have no short term plan to work on it but I will double check with the team.

**Comment by Evangelink** [comment]
Hi @tijana88,

So we had a chat about this and we decided not to do anything for now on.
