### ISSUE TITLE
Rule S122: ignore simple one-liner statements

### ISSUE THREAD

**Issue by Chelaris182** [SonarSource/sonar-csharp#892]
### Description
I'd like to make a proposal to add new exceptions to the rule and allow simple one-liners with "return" or "throw" statements only.
There is also a good discussion in corefx https://github.com/dotnet/corefx/issues/381 where they agreed to use oneliners for preconditions.

### Repro steps

```c#
if (someCondition) throw new ArgumentNullException();
```

### Expected behavior

No violations.

### Actual behavior

S122 violation.

### Related information

* SonarC# 6.5.0.3766
* Visual Studio Version 2017

**Comment by michalb-sonar** [comment]
Thanks for suggestion @Chelaris182. We have considered that, but decided not to relax the rule. The main reason is that this is quite subjective - even the discussion you pointed to wasn't quite unanimous. I'm afraid at the moment the only option if you disagree is to disable the rule.
