### ISSUE TITLE
S2339 (Public constant members should not be used) - triggered for cases that cannot be fixed

### ISSUE THREAD

**Issue by ohadschn** [SonarSource/sonar-csharp#919]
Consider:

```cs
class Foo
{
    public const string Bar = "Bar";
    
    [MyAttribute(Bar)]
    public void F();
}
```

S2339 (_Public constant members should not be used_) will be triggered, proposing a change that cannot be made because attribute arguments must be static expressions (CS0182).

**Comment by valhristov** [comment]
Private `const` can be used in an attribute on a class declaration, even though it seems the attribute is declared before the constant. I am pretty sure it will work on methods too:
```
[MyAttribute(Bar)]
public class Foo
{
    private const string Bar = "Bar";
}
```

**Comment by Evangelink** [comment]
I confirm this is working.
```
[System.ComponentModel.Category(Bar)]
public class Foo
{
    private const string Bar = "Bar";

    [System.ComponentModel.Category(Bar)]
    public void MyMethod()
    {
    }
}
```

**Comment by ohadschn** [comment]
I can't make it private:

public class Constants
{
    public string Bar = "Bar";
}

class Foo
{    
    [MyAttribute(Constants.Bar)]
    public void F();
}

**Comment by valhristov** [comment]
The idea of this rule is to protect the users of your library from changes in your constants (when they update to a new version, but don't recompile, which could easily happen with nugets and binding redirects). Please, see the detailed explanation here: [what-is-the-difference-between-const-and-readonly](https://stackoverflow.com/questions/55984/what-is-the-difference-between-const-and-readonly).

To resolve the problem you have few choices:
- if the Constants class is supposed to be used only within your application, you could make it internal and add InternalsVisible attributes where needed
- disable the rule

**Comment by ohadschn** [comment]
Thank you @valhristov, I am aware of the rationale behind the rule and actually agree with it.
I suppose using `internal` is a reasonable compromise.
