### ISSUE TITLE
Fix S2259: Rule should not fire on nameof(a.P) case

### ISSUE THREAD

**Issue by hanabi1224** [SonarSource/sonar-csharp#923]
### Description

S2259 should not fire on nameof(a.P) case since nameof will evaluate at compile time
('a' is null on at least one execution path)

* SonarC# Version: 6.6.0.3969
* Visual Studio Version: 15.4.3

**Comment by michalb-sonar** [comment]
Thanks @hanabi1224. You are right, that shouldn't raise.
