### ISSUE TITLE
NullReferenceException in SonarAnalyzer.Rules.CSharp.UseValueParameter

### ISSUE THREAD

**Issue by llehn** [SonarSource/sonar-csharp#948]
I get this exception:

    Error	AD0001	Analyzer 'SonarAnalyzer.Rules.CSharp.UseValueParameter' threw an exception of 
    type 'System.NullReferenceException' with message 'Der Objektverweis wurde nicht auf eine 
    Objektinstanz festgelegt.'.	Kardex.Communication.Protocol.Opc.Ua.Api		1	Active	Analyzer 
    'SonarAnalyzer.Rules.CSharp.UseValueParameter' threw the following exception:
    'Exception occurred with following context:
    Compilation: Kardex.Communication.Protocol.Opc.Ua.Api
    ISymbol: set_Path (Method)
    SyntaxTree: 
    C:\Dev\projects\tic\src\Kardex.Communication.Protocol.Opc.Ua.Api\Uri\OpcUaPathBuilder.cs
    SyntaxNode: set => segments = Split(value); ... [AccessorDeclarationSyntax]@[1860..1891) (61,12)-
    (61,43)

    System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
       bei SonarAnalyzer.Rules.CSharp.UseValueParameter.<>c.Initialize>b__5_0(CodeBlockStartAnalysisContext`1 cbc)
       bei SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass5_0`1.<RegisterCodeBlockStartActionInNonGenerated>b__0(CodeBlockStartAnalysisContext`1 c)
       bei SonarAnalyzer.Helpers.SonarAnalysisContext.<>c__DisplayClass11_0`1.<RegisterCodeBlockStartAction>b__0(CodeBlockStartAnalysisContext`1 c)
       bei Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__47`6.<ExecuteBlockActionsCore>b__47_1(ValueTuple`5 data)
       bei Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg]
    (DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)

The code its analyzing (set_Path) is this property:

    public new string Path
    {
       get => pathBuilder.Path;
       set => pathBuilder.Path = value;
    }

* SonarC# Version
6.6.0.3969
* Visual Studio Version
2017 15.4
* If running through the Scanner for MSBuild, its version

**Comment by llehn** [comment]
The exception occurs only with prerelease version of dotnet sdk 2.2.1 preview

With release version no errors occurs

**Comment by Evangelink** [comment]
Thanks for the heads up!

**Comment by llehn** [comment]
Now that dotnet sdk 2.1.2 is installed by visual studio, the exception occurs again.

This is a blocker. My projects don't build now.

**Comment by llehn** [comment]
Updated to 6.7, this goes away, but another build breaker shows up. I'll create an issue

**Comment by Evangelink** [comment]
Hi @llehn, thx for this update.

**Comment by RalfKoban** [comment]
Hi,

I just upgraded by VS to **Microsoft Visual Studio Enterprise 2017 Version 15.5.1** and now I'm getting following exception reported:

Error	AD0001	Analyzer 'SonarAnalyzer.Rules.CSharp.UseValueParameter' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

There is no further stacktrace available, so I'm not sure whether this is the same error or another one.

My Sonar Analyzer version is 6.7.0.4267, my C# project uses .NET 4.7.1.
