### ISSUE TITLE
DotCover is not imported

### ISSUE THREAD

**Issue by akuryan** [SonarSource/sonar-csharp#967]
### Description

I am running SonarQube v.5.6.5 with SonarC# v.6.6.0.3969 installed (recently updated from v.5). Now, I observe a problem - dotCover reports is not imported (despite being reported in runner)

### Repro steps

Please, see 
[log.txt](https://github.com/SonarSource/sonar-csharp/files/1488937/log.txt).

Parameters, used to start scanner is `MSBuild.SonarQube.Runner.exe begin /key:%sonar.projectKey% /name:%sonar.projectName%; /version:%build.number% /d:sonar.host.url=%sonar.url% /d:sonar.login=%sonar.authKey%  /d:sonar.sourceEncoding="UTF-8" /d:sonar.exclusions="**/packages/**,**/*.min.js,**/jquery*.js,**/Model/Model.gen.cs,**/*-min.js,**/*.generated.cs,**/*.designer.cs,**/*.min.css,**/*.xml,**/gulpfile.js,**/scripts/ai.*.js ,**/Umbraco/**,**/umbraco/**,**/usync/**,**/uSync/**,**/App_Plugins/**,**/umbraco_client/**,**/Umbraco_Client/**,**/static/styleguide/**,**/static/public/_data/**,**/static/js/lib/**,**/_annotations/**,**/source/_data/**,**/source/js/**,**/source/_data/**,**/node_modules/**,**/patternlab-*.js,/static/public/css/style.css" /d:sonar.resharper.cs.reportPath="D:\w\3\64205b8b4348228b\resharper.xml" /d:sonar.resharper.solutionFile="D:\w\3\64205b8b4348228b\Sources\TestProjects.sln" /d:sonar.cs.dotcover.reportsPaths="D:\t\3\buildTmp\dotCover.html" `
Scanner is started from 

### Expected behavior

Same as with SonarC# v.5 - coverage report displayed at project dashboard

### Actual behavior

Coverage report is not displayed

### Known workarounds

Please provide a description of any known workarounds.

### Related information

* SonarC# Version v.6.6.0.3969
* Visual Studio Version 2015
* If running through the Scanner for MSBuild, its version 3.0.2

**Comment by Evangelink** [comment]
@akuryan I am sorry this issue didn't receive the proper care. Are you still experiencing issues with the new versions?

**Comment by akuryan** [comment]
Seems to be fixed now. Sorry, forgot to close it

**Comment by Evangelink** [comment]
Np! Thanks for the answer.
