### ISSUE TITLE
Fix S3532: default clauses with comments should not be reported

### ISSUE THREAD

**Issue by HamsterExAstris** [SonarSource/sonar-csharp#992]
### Description

Rule S131 ('"switch" statements should end with a "default" clause') triggers on a switch statement when a default case does not exist. Adding a clause that "contain(s) a suitable comment as to why no action is taken" is supposed to be a valid resolution for S131 per its descriptive text.

Rule S3532 ('Empty "default" clauses should be removed') triggers on a switch statement when a default case has no actual code. Even if there is a comment (per S131's resolution suggestions), this rule will still trigger.

### Repro steps

Run the SonarQube scanner against the attached solution.

[SonarQubeSwitching.zip](https://github.com/SonarSource/sonar-csharp/files/1503493/SonarQubeSwitching.zip)

### Expected behavior

When the default case contains a comment, S3532 is not triggered.

### Actual behavior

A default case containing a comment but no other code triggers rule S3532.

### Known workarounds

None.

### Related information

* SonarC# 5.10.1, though I don't see either of these rules as having been updated in a subsequent release
* Visual Studio 2015
* Scanner for MSBuild, 2.3.2.573

**Comment by valhristov** [comment]
Thanks for pointing this problem, we will fix it in the near future.
